### ISSUE TITLE
Onediff not work when using IPAdapter Tiled Batch

### ISSUE THREAD

**Issue by Einssam** [siliconflow/onediff#1006]
#### I want check whether the unet defined in infer_compiler_registry/registry_comfy/openaimodel.py is used or not. I find this unet is not used when IPAdapter Tiled Batch is used in my workflow. By the way, onediff works when I not use IPAdapter Tiled Batch.
<img width="1052" alt="image" src="https://github.com/siliconflow/onediff/assets/94092802/9419f3d3-03bb-4412-b121-5a02304f32eb">

####  OneFlow version info if you have installed oneflow
Run `python -m oneflow --doctor` and paste it here.

version: 0.9.1.dev20240625+cu121
git_commit: ec7b682
cmake_build_type: Release
rdma: True
mlir: True
enterprise: False

### How To Reproduce
Steps to reproduce the behavior(code or script):

**Comment by Einssam** [comment]
这个报错我们已经解决，更换ipadapter的commit即可。我们现在遇到的问题是IPAdapter Tiled Batch时，ksampler时候并没有使用onediff中的unet；而不使用IPAdapter Tiled Batch时一切正常

**Comment by lijunliangTG** [comment]
请问您的 ComfyUI-AnimateDiff-Evolved 插件的git commit是？

**Comment by Einssam** [comment]
> 请问您的 ComfyUI-AnimateDiff-Evolved 插件的git commit是？

2d4164271634476627aae31fbec251ca748a0ae0

**Comment by lijunliangTG** [comment]
当我尝试用最新的comfyui (29c2e26) 、IPAdapter_plus (8208e27) 和AnimateDiff-Evolved (1b660e5) 来复现代码时，发现接口不兼容报错如下：

<details>

<summary> 复现详情 </summary>

![onediff_fuyuan](https://github.com/user-attachments/assets/bd7c544e-74f9-4ea0-8383-ac9dddb1ccde)

报错如下：
```
Traceback (most recent call last):
  File "/data/home/lijunliang/project/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/data/home/lijunliang/project/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/data/home/lijunliang/project/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/data/home/lijunliang/project/ComfyUI/nodes.py", line 1373, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "/data/home/lijunliang/project/ComfyUI/nodes.py", line 1343, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "/data/home/lijunliang/project/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved/animatediff/sampling.py", line 520, in motion_sample
    latents = orig_comfy_sample(model, noise, *args, **kwargs)
  File "/data/home/lijunliang/project/ComfyUI/comfy/sample.py", line 43, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/data/home/lijunliang/project/ComfyUI/comfy/samplers.py", line 801, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/data/home/lijunliang/project/ComfyUI/comfy/samplers.py", line 703, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "/data/home/lijunliang/project/ComfyUI/comfy/samplers.py", line 690, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "/data/home/lijunliang/project/ComfyUI/comfy/samplers.py", line 669, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "/data/home/lijunliang/project/ComfyUI/comfy/samplers.py", line 574, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "/data/home/lijunliang/anaconda3/envs/sd2/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/home/lijunliang/project/ComfyUI/comfy/k_diffusion/sampling.py", line 600, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "/data/home/lijunliang/project/ComfyUI/comfy/samplers.py", line 297, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "/data/home/lijunliang/project/ComfyUI/comfy/samplers.py", line 656, in __call__
    return self.predict_noise(*args, **kwargs)
  File "/data/home/lijunliang/project/ComfyUI/comfy/samplers.py", line 659, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "/data/home/lijunliang/project/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved/animatediff/sampling.py", line 625, in evolved_sampling_function
    cond_pred, uncond_pred = calc_cond_uncond_batch_wrapper(model, [cond, uncond_], x, timestep, model_options)
  File "/data/home/lijunliang/project/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved/animatediff/sampling.py", line 904, in calc_cond_uncond_batch_wrapper
    return comfy.samplers.calc_cond_batch(model, conds, x_in, timestep, model_options)
  File "/data/home/lijunliang/project/ComfyUI/custom_nodes/onediff_comfy_nodes/modules/sd_hijack_utils.py", line 58, in hijacked_method
    return self(*args, **kwargs)
  File "/data/home/lijunliang/project/ComfyUI/custom_nodes/onediff_comfy_nodes/modules/sd_hijack_utils.py", line 93, in __call__
    return sub_func(self._orig_func, *args, **kwargs)
  File "/data/home/lijunliang/project/ComfyUI/custom_nodes/onediff_comfy_nodes/modules/oneflow/hijack_samplers.py", line 122, in calc_cond_batch_of
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "/data/home/lijunliang/project/ComfyUI/comfy/model_base.py", line 114, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "/data/home/lijunliang/anaconda3/envs/sd2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/home/lijunliang/anaconda3/envs/sd2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1582, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/data/home/lijunliang/project/onediff/src/onediff/infer_compiler/backends/oneflow/online_quantization_utils.py", line 61, in wrapper
    output = func(self, *args, **kwargs)
  File "/data/home/lijunliang/project/onediff/src/onediff/infer_compiler/backends/oneflow/args_tree_util.py", line 66, in wrapper
    output = func(self, *mapped_args, **mapped_kwargs)
  File "/data/home/lijunliang/project/onediff/src/onediff/infer_compiler/backends/oneflow/deployable_module.py", line 33, in wrapper
    return func(self, *args, **kwargs)
  File "/data/home/lijunliang/project/onediff/src/onediff/infer_compiler/backends/oneflow/graph_management_utils.py", line 118, in wrapper
    ret = func(self, *args, **kwargs)
  File "/data/home/lijunliang/project/onediff/src/onediff/infer_compiler/backends/oneflow/deployable_module.py", line 144, in forward
    output = dpl_graph(*args, **kwargs)
  File "/data/home/lijunliang/anaconda3/envs/sd2/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 295, in __call__
    self._compile(*args, **kwargs)
  File "/data/home/lijunliang/anaconda3/envs/sd2/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 861, in _compile
    return self._dynamic_input_graph_cache._compile(*args, **kwargs)
  File "/data/home/lijunliang/anaconda3/envs/sd2/lib/python3.10/site-packages/oneflow/nn/graph/cache.py", line 121, in _compile
    return graph._compile(*args, **kwargs)
  File "/data/home/lijunliang/anaconda3/envs/sd2/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 865, in _compile
    return self._compile_new(*args, **kwargs)
  File "/data/home/lijunliang/anaconda3/envs/sd2/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 884, in _compile_new
    _, eager_outputs = self.build_graph(*args, **kwargs)
  File "/data/home/lijunliang/anaconda3/envs/sd2/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 1429, in build_graph
    outputs = self.__build_graph(*args, **kwargs)
  File "/data/home/lijunliang/anaconda3/envs/sd2/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 1577, in __build_graph
    outputs = self.build(*lazy_args, **lazy_kwargs)
  File "/data/home/lijunliang/project/onediff/src/onediff/infer_compiler/backends/oneflow/graph.py", line 20, in build
    return self.model(*args, **kwargs)
  File "/data/home/lijunliang/anaconda3/envs/sd2/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 188, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/data/home/lijunliang/anaconda3/envs/sd2/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 238, in __block_forward
    result = unbound_forward_of_module_instance(self, *args, **kwargs)
  File "/data/home/lijunliang/project/ComfyUI/custom_nodes/onediff_comfy_nodes/modules/oneflow/infer_compiler_registry/register_comfy/openaimodel.py", line 97, in forward
    h = forward_timestep_embed(
  File "/data/home/lijunliang/project/onediff/src/onediff/infer_compiler/backends/oneflow/import_tools/dyn_mock_mod.py", line 65, in proxy_func
    return sub_module()(*args, **kwargs)
  File "/data/home/lijunliang/project/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved/animatediff/sampling.py", line 159, in forward_timestep_embed
    x = layer(x, context)
  File "/data/home/lijunliang/anaconda3/envs/sd2/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 188, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/data/home/lijunliang/anaconda3/envs/sd2/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 238, in __block_forward
    result = unbound_forward_of_module_instance(self, *args, **kwargs)
  File "/data/home/lijunliang/project/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved/animatediff/motion_module_ad.py", line 751, in forward
    return self.temporal_transformer(input_tensor, encoder_hidden_states, attention_mask, self.view_options, mm_kwargs)
  File "/data/home/lijunliang/anaconda3/envs/sd2/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 188, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/data/home/lijunliang/anaconda3/envs/sd2/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 238, in __block_forward
    result = unbound_forward_of_module_instance(self, *args, **kwargs)
TypeError: TemporalTransformer3DModel_OF.forward() takes from 2 to 5 positional arguments but 6 were given
```

</details>

**Comment by lijunliangTG** [comment]
您好，您可以通过更新OneDiff到最新的版本，并且将 ComfyUI_IPAdapter_plus 更新到 ``` 8208e27 ```， ComfyUI-AnimateDiff-Evolved 更新到 ``` 1b660e5 ``` 来使用OneDiff的Unet
![img_v3_02cq_711f47e0-6d56-4f4f-81cc-cd8295e8f92g](https://github.com/user-attachments/assets/7a170a3d-65f9-4a69-b071-ccd0e1ace48c)

**Comment by Einssam** [comment]
> 您好，您可以通过更新OneDiff到最新的版本，并且将 ComfyUI_IPAdapter_plus 更新到 `8208e27`， ComfyUI-AnimateDiff-Evolved 更新到 `1b660e5` 来使用OneDiff的Unet ![img_v3_02cq_711f47e0-6d56-4f4f-81cc-cd8295e8f92g](https://private-user-images.githubusercontent.com/117806079/348583570-7a170a3d-65f9-4a69-b071-ccd0e1ace48c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMTA4MzAsIm5iZiI6MTcyMTAxMDUzMCwicGF0aCI6Ii8xMTc4MDYwNzkvMzQ4NTgzNTcwLTdhMTcwYTNkLTY1ZjktNGE2OS1iMDcxLWNjZDBlMWFjZTQ4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQwMjI4NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZjY2MzA1NGMxOThiNzc5NDUyODA2N2M1ZDY5MTVhMTUxMWFkMmVlZTNhNzBjNWZkYTE4YzAzNzQzNGI2ZmM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C9sUNZT1RmUsGWZlvuyra0kdhSt1SzfLwtLLIhuskzY)

好的，我试一下

**Comment by Einssam** [comment]
> 1b660e5

<img width="815" alt="image" src="https://github.com/user-attachments/assets/63dcf45d-094b-4c55-9073-d7ca3422b3d5">
我把相应包更新以后，出现了这个错误。之前遇到这个报错的时候，是因为ipadapter包的不兼容，不知道是不是提供的这几个commit有不兼容的地方？

**Comment by lijunliangTG** [comment]
您可以尝试一下把 comfyui切换到29c2e26版本试试，另外更新完OneDiff之后需要重新执行``` cp -r onediff_comfy_nodes path/to/ComfyUI/custom_nodes/ ```

**Comment by Einssam** [comment]
> 29c2e26

还是一样的报错

**Comment by lijunliangTG** [comment]
> 这个报错我们已经解决，更换ipadapter的commit即可。我们现在遇到的问题是IPAdapter Tiled Batch时，ksampler时候并没有使用onediff中的unet；而不使用IPAdapter Tiled Batch时一切正常

通过如图所示替换节点，可以发现加速时采用的是onediff的unet
![0ca9659be27e60d42e2ac5d7edc9aed](https://github.com/user-attachments/assets/c8397c5d-bd4a-4717-a44d-5d66389680a1)

| loadcheckpoint  | OneDiffloadcheckpoint |
|:-----------------:|:--------------------------:|
| ![b9f68ac33f5d1710cfcaf058da4d9b6](https://github.com/user-attachments/assets/69a49180-b8fa-4d4e-b8a6-a93feda50698) | ![27c49242f0de23288e8e1be725a73b1](https://github.com/user-attachments/assets/720502c0-587c-43eb-8a36-d04dd154f5d0) |
