### ISSUE TITLE
save_pipe failed

### ISSUE THREAD

**Issue by maidabu** [siliconflow/onediff#1021]
Save the optimized pipe failed.
Test on A10 with torch2.3.0+cuda12.1, with command:
python3 benchmarks/text_to_image.py   --model runwayml/stable-diffusion-v1-5   --height 512 --width 512     --steps 20   --output-image ./stable-diffusion-v1-5-compile.png   --prompt "beautiful scenery nature glass bottle landscape, , purple galaxy bottle,"   --compiler nexfort   --compiler-config '{"mode": "cudagraphs:benchmark:max-autotune:low-precision:cache-all", "memory_format": "channels_last", "options": {"inductor.optimize_linear_epilogue": false, "overrides.conv_benchmark": true, "overrides.matmul_allow_tf32": true}}'   --seed 1  --variant "fp16"   --print-output

I only add two lines code at the last of main() function.
>> from onediffx import save_pipe
>> save_pipe(pipe, "of_sd1.5_graph")

Traceback (most recent call last):
  File "/onediff/benchmarks/text_to_image.py", line 427, in <module>
    main()
  File "/onediff/benchmarks/text_to_image.py", line 423, in main
    save_pipe(pipe, "of_sd1.5_graph")
  File "/onediff/onediff_diffusers_extensions/onediffx/compilers/diffusion_pipeline_compiler.py", line 154, in save_pipe
    and obj._deployable_module_dpl_graph is not None
  File "/onediff/src/onediff/infer_compiler/backends/nexfort/deployable_module.py", line 25, in __getattr__
    return getattr(self._deployable_module_model, name)
  File "/workspace/miniconda/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 222, in __getattr__
    return getattr(self._orig_mod, name)
  File "/workspace/miniconda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1709, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CLIPTextModel' object has no attribute '_deployable_module_dpl_graph'

**Comment by strint** [comment]
You are using the nexfort backend(based on  torch compile stack), and  it's compilation cache works like this: https://github.com/siliconflow/onediff/tree/main/src/onediff/infer_compiler/backends/nexfort#compilation-cache-speeds-up-recompilation

We haven't provided the save_pipe API for nexfort yet, you need to use the `TORCHINDUCTOR_CACHE_DIR` with nexfort for now.
