### ISSUE TITLE
[Bug] !!! Exception during processing!!! 

### ISSUE THREAD

**Issue by hashmap521** [siliconflow/onediff#1082]
### Your current environment information

Cache lookup: Key='ef4e9fbc-bdd2-44ab-8e14-5e966ad3ca11', Cached Model Type='<class 'comfy.model_base.BaseModel'>'
Cache lookup: Key='5645c6f1-d0a3-4566-b071-7da1bd597e1d', Cached Model Type='<class 'NoneType'>'
!!! Exception during processing!!! 
Traceback (most recent call last):
  File "/home/qrcode/comfyui/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/qrcode/comfyui/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/qrcode/comfyui/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/qrcode/comfyui/comfyui-env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/qrcode/comfyui/ComfyUI/custom_nodes/onediff_comfy_nodes/_nodes.py", line 253, in onediff_load_checkpoint
    vae = self.speedup(
  File "/home/qrcode/comfyui/comfyui-env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/qrcode/comfyui/ComfyUI/custom_nodes/onediff_comfy_nodes/_nodes.py", line 80, in speedup
    return (booster(model, *args, **kwargs),)
  File "/home/qrcode/comfyui/ComfyUI/custom_nodes/onediff_comfy_nodes/modules/booster_scheduler.py", line 61, in __call__
    return self.compile(model=model, ckpt_name=ckpt_name, **kwargs)
  File "/home/qrcode/comfyui/ComfyUI/custom_nodes/onediff_comfy_nodes/modules/booster_scheduler.py", line 24, in wrapper
    self.cache_service.put(cached_model_key, cached_model)
  File "/home/qrcode/comfyui/ComfyUI/custom_nodes/onediff_comfy_nodes/modules/booster_cache.py", line 74, in put
    cached_model = get_cached_model(model)
  File "/usr/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/qrcode/comfyui/ComfyUI/custom_nodes/onediff_comfy_nodes/modules/booster_cache.py", line 60, in _
    if is_using_oneflow_backend(model):
  File "/home/qrcode/comfyui/ComfyUI/custom_nodes/onediff_comfy_nodes/modules/oneflow/utils/booster_utils.py", line 88, in is_using_oneflow_backend
    raise RuntimeError("")
RuntimeError

### 🐛 Describe the bug

![WechatIMG428](https://github.com/user-attachments/assets/bc332f8e-bd85-4a9e-8440-3e03c484cd6a)

**Comment by rfan-debug** [comment]
We're running into the same bug with the newest commit of comfy UI node: https://github.com/siliconflow/onediff/commit/e7713590d3c7ffc9376b081c96abc696e8c60f56. Is there any solution for it?

**Comment by chenjinxuan** [comment]
I have also encountered the same problem, have you solved it？
