### ISSUE TITLE
Saving compiled graph for VAE fails

### ISSUE THREAD

**Issue by isidentical** [siliconflow/onediff#452]
Saving the pre-compiled graph (which includes variation of sizes, from `1024x576` to `576x1024`), the unet saving/loading works fine. VAE can also be compiled and saved, but when loading the VAE, I consistently get this error:
 
```
2023-12-22 23:17:08.433 [stdout   ] Error while loading compiled graph
2023-12-22 23:17:08.433 [stdout   ] 
2023-12-22 23:17:08.435 [stderr   ] Traceback (most recent call last):
2023-12-22 23:17:08.435 [stderr   ]   File "/home/cicero/projects/serverless-registry/registry/image/fast_sdxl/inference.py", line 144, in get_pipe
2023-12-22 23:17:08.436 [stderr   ]   File "/root/.cache/isolate/virtualenv/99cafc972772796ccb1a1979a444f847491bfbbd387f4c257463f20df6ee495f/lib/python3.11/site-packages/onediff/infer_compiler/with_oneflow_compile.py", line 283, in load_graph
2023-12-22 23:17:08.436 [stderr   ]     self.get_graph().warmup_with_load(file_path, device)
2023-12-22 23:17:08.436 [stderr   ]   File "/root/.cache/isolate/virtualenv/99cafc972772796ccb1a1979a444f847491bfbbd387f4c257463f20df6ee495f/lib/python3.11/site-packages/onediff/infer_compiler/utils/cost_util.py", line 46, in clocked
2023-12-22 23:17:08.436 [stderr   ]     return func(*args, **kwargs)
2023-12-22 23:17:08.436 [stderr   ]            ^^^^^^^^^^^^^^^^^^^^^
2023-12-22 23:17:08.436 [stderr   ]   File "/root/.cache/isolate/virtualenv/99cafc972772796ccb1a1979a444f847491bfbbd387f4c257463f20df6ee495f/lib/python3.11/site-packages/onediff/infer_compiler/with_oneflow_compile.py", line 331, in warmup_with_load
2023-12-22 23:17:08.436 [stderr   ]     self.load_runtime_state_dict(state_dict)
2023-12-22 23:17:08.436 [stderr   ]   File "/root/.cache/isolate/virtualenv/99cafc972772796ccb1a1979a444f847491bfbbd387f4c257463f20df6ee495f/lib/python3.11/site-packages/oneflow/nn/graph/graph.py", line 1156, in load_runtime_state_dict
2023-12-22 23:17:08.436 [stderr   ]     return self._dynamic_input_graph_cache.load_runtime_state_dict(
2023-12-22 23:17:08.436 [stderr   ]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-22 23:17:08.436 [stderr   ]   File "/root/.cache/isolate/virtualenv/99cafc972772796ccb1a1979a444f847491bfbbd387f4c257463f20df6ee495f/lib/python3.11/site-packages/oneflow/nn/graph/cache.py", line 234, in load_runtime_state_dict
2023-12-22 23:17:08.436 [stderr   ]     graph.load_runtime_state_dict(
2023-12-22 23:17:08.436 [stderr   ]   File "/root/.cache/isolate/virtualenv/99cafc972772796ccb1a1979a444f847491bfbbd387f4c257463f20df6ee495f/lib/python3.11/site-packages/oneflow/nn/graph/graph.py", line 1294, in load_runtime_state_dict
2023-12-22 23:17:08.436 [stderr   ]     self._c_nn_graph.init_runtime()
2023-12-22 23:17:08.436 [stderr   ] oneflow._oneflow_internal.exception.Exception: Check failed: (512 >= 1024): 
2023-12-22 23:17:08.436 [stderr   ]   File "/root/.cache/isolate/virtualenv/99cafc972772796ccb1a1979a444f847491bfbbd387f4c257463f20df6ee495f/lib/python3.11/site-packages/oneflow/_oneflow_internal.cpython-311-x86_64-linux-gnu.so", line <unknown>, in 
2023-12-22 23:17:08.436 [stderr   ]   File "/root/.cache/isolate/virtualenv/99cafc972772796ccb1a1979a444f847491bfbbd387f4c257463f20df6ee495f/lib/python3.11/site-packages/oneflow/_oneflow_internal.cpython-311-x86_64-linux-gnu.so", line <unknown>, in 
2023-12-22 23:17:08.436 [stderr   ]   File "/root/.cache/isolate/virtualenv/99cafc972772796ccb1a1979a444f847491bfbbd387f4c257463f20df6ee495f/lib/python3.11/site-packages/oneflow/../oneflow.libs/liboneflow-6429e1b8.so", line <unknown>, in NNGraph::InitRuntime()
2023-12-22 23:17:08.436 [stderr   ]   File "/root/.cache/isolate/virtualenv/99cafc972772796ccb1a1979a444f847491bfbbd387f4c257463f20df6ee495f/lib/python3.11/site-packages/oneflow/../oneflow.libs/liboneflow-6429e1b8.so", line <unknown>, in Runtime::Runtime(Plan const&, std::unordered_map<std::string, vm::EagerBlobObject*, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, vm::EagerBlobObject*> > > const&)
2023-12-22 23:17:08.436 [stderr   ]   File "oneflow/core/register/register_manager.cpp", line 147, in AddPlan
2023-12-22 23:17:08.436 [stderr   ]     CHECK_GE_OR_THROW(var_blob->AlignedByteSizeOfBlobBody(), mem_block.mem_size())
2023-12-22 23:17:08.437 [stderr   ] Error Type: oneflow.ErrorProto.check_failed_error
```

Using the latest version of onediff (from the deepcache branch) and oneflow for CU121

**Comment by strint** [comment]
@isidentical, please run and paste the result here.
```
python -m oneflow --doctor
```
We will try to reproduce this.

By the way, what pipeline are you using?

**Comment by isidentical** [comment]
Its the StableDiffusionXLDeepCache pipeline from one of the last PRs (with
a few modifications to make it work although nothing that changes the
architecture).

**Comment by strint** [comment]
> Its the StableDiffusionXLDeepCache pipeline

OK.

@isidentical 

Please run this in your enviroment to get the oneflow version info:
```
python -m oneflow --doctor
```

**Comment by isidentical** [comment]
```
2023-12-23 16:07:53.152 [stdout   ] path: ['/root/.cache/isolate/virtualenv/99cafc972772796ccb1a1979a444f847491bfbbd387f4c257463f20df6ee495f/lib/python3.11/site-packages/oneflow']
2023-12-23 16:07:53.152 [stdout   ] version: 0.9.1.dev20231222+cu121
2023-12-23 16:07:53.152 [stdout   ] git_commit: 16189c9
2023-12-23 16:07:53.152 [stdout   ] cmake_build_type: Release
2023-12-23 16:07:53.152 [stdout   ] rdma: True
2023-12-23 16:07:53.152 [stdout   ] mlir: True
```

**Comment by strint** [comment]
@isidentical 
Thanks a lot, we have reproduced this bug and is working on it.

**Comment by strint** [comment]
@isidentical 
Please refer to this PR to fix vae load: https://github.com/siliconflow/onediff/pull/470#discussion_r1436922683

### upcast_vae cause the loading problem

https://github.com/huggingface/diffusers/blob/c75144901135fd9621a8729946c0570af2582329/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py#L685

https://github.com/huggingface/diffusers/blob/c75144901135fd9621a8729946c0570af2582329/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py#L1276

before vae run：
```
self.vae.to(dtype=torch.float32)
```
run and compile vae：
 graph compiled with   fp32 tensor

after vae run：
```
self.vae.to(dtype=torch.float16)
```

When saving graph, graph save the meta data of vae parameter with fp32.
When loading graph, graph load the meta data of vae parameter with fp32, but outside the pipe run, vae parameter is fp16 which case the graph loading check error.

So we do this before loading to avoid the check error:
```
if base.vae.dtype == torch.float16 and base.vae.config.force_upcast:
    base.upcast_vae()
```

We will try to fix this in graph load later to avoid adding this code.
