### ISSUE TITLE
cannot run Stable-Diffusion-WebUI-OneDiff example

### ISSUE THREAD

**Issue by arthursunbao** [siliconflow/onediff#483]
### Describe the bug
cannot run Stable-Diffusion-WebUI-OneDiff example according to the README 
https://github.com/siliconflow/onediff/blob/main/onediff_sd_webui_extensions/README.md

#### OneDiff git commit id
[04f37b5](https://github.com/siliconflow/onediff/commit/04f37b59752beaa5f7ab06bc8e88a018dd0799fe)

####  OneFlow version info
Run `python -m oneflow --doctor` and paste it here.

Ignoring PCI device with non-16bit domain.
Pass --enable-32bits-pci-domain to configure to support such devices
(warning: it would break the library ABI, don't enable unless really needed).
path: ['/data/miniconda3/envs/sd-webui/lib/python3.10/site-packages/oneflow']
version: 0.9.0
git_commit: 381b12c
cmake_build_type: Release
rdma: True
mlir: True

### How To Reproduce
following the steps of this README:
https://github.com/siliconflow/onediff/blob/main/onediff_sd_webui_extensions/README.md

and when it comes to  python webui.py --port 8080, it gets this error

### The complete error message

python webui.py --port 8080
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Ignoring PCI device with non-16bit domain.
Pass --enable-32bits-pci-domain to configure to support such devices
(warning: it would break the library ABI, don't enable unless really needed).
*** Error loading script: onediff.py
    Traceback (most recent call last):
      File "/data/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/data/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/data/stable-diffusion-webui/extensions/onediff_sd_webui_extensions/scripts/onediff.py", line 8, in <module>
        from compile_sgm import compile_sgm_unet
      File "/data/stable-diffusion-webui/extensions/onediff_sd_webui_extensions/compile_sgm.py", line 2, in <module>
        from onediff.infer_compiler import oneflow_compile, register
      File "/data/onediff/src/onediff/infer_compiler/__init__.py", line 5, in <module>
        from .utils.patch_for_compiler import *  # TODO:
      File "/data/onediff/src/onediff/infer_compiler/utils/__init__.py", line 3, in <module>
        from .model_inplace_assign import TensorInplaceAssign
      File "/data/onediff/src/onediff/infer_compiler/utils/model_inplace_assign.py", line 4, in <module>
        from onediff.infer_compiler.with_oneflow_compile import DeployableModule
      File "/data/onediff/src/onediff/infer_compiler/with_oneflow_compile.py", line 9, in <module>
        from .transform.manager import transform_mgr
      File "/data/onediff/src/onediff/infer_compiler/transform/__init__.py", line 2, in <module>
        from .manager import transform_mgr
      File "/data/onediff/src/onediff/infer_compiler/transform/manager.py", line 8, in <module>
        from ..import_tools.importer import LazyMocker
      File "/data/onediff/src/onediff/infer_compiler/import_tools/__init__.py", line 2, in <module>
        from .importer import import_module_from_path, LazyMocker
      File "/data/onediff/src/onediff/infer_compiler/import_tools/importer.py", line 6, in <module>
        from oneflow.mock_torch import DynamicMockModule
    ImportError: cannot import name 'DynamicMockModule' from 'oneflow.mock_torch' (/data/miniconda3/envs/sd-webui/lib/python3.10/site-packages/oneflow/mock_torch/__init__.py)

---
Loading weights [6ce0161689] from /data/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.safetensors
Running on local URL:  http://127.0.0.1:8080
Creating model from config: /data/stable-diffusion-webui/configs/v1-inference.yaml
Traceback (most recent call last):
  File "/data/stable-diffusion-webui/webui.py", line 162, in <module>
    webui()
  File "/data/stable-diffusion-webui/webui.py", line 79, in webui
    app, local_url, share_url = shared.demo.launch(
  File "/data/miniconda3/envs/sd-webui/lib/python3.10/site-packages/gradio/blocks.py", line 1971, in launch
    raise ValueError(
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost.
Applying attention optimization: Doggettx... done.
Model loaded in 18.3s (load weights from disk: 0.6s, create model: 0.7s, apply weights to model: 16.3s, apply half(): 0.3s, move model to device: 0.1s, calculate empty prompt: 0.2s).

**Comment by strint** [comment]
> ImportError: cannot import name 'DynamicMockModule' from 'oneflow.mock_torch' (/data/miniconda3/envs/sd-webui/lib/python3.10/site-packages/oneflow/mock_torch/init.py)

It seem an oneflow version problem. Please re-install the latest oneflow as the follow instruciton: https://github.com/siliconflow/onediff?tab=readme-ov-file#1-install-oneflow

**Comment by fpzh2011** [comment]
@vtnhan1309 please install oneflow as follows:
```bash
python3 -m pip install --pre oneflow -f https://oneflow-pro.oss-cn-beijing.aliyuncs.com/branch/community/cu118
```

**Comment by vtnhan1309** [comment]
@fpzh2011 , Sorry, I installed OneFlow by this command but I still cannot import DynamicMockModule

> @vtnhan1309 please install oneflow as follows:
> 
> ```shell
> python3 -m pip install --pre oneflow -f https://oneflow-pro.oss-cn-beijing.aliyuncs.com/branch/community/cu118
> ```

**Comment by vtnhan1309** [comment]
@fpzh2011 , It works, thank you !

**Comment by strint** [comment]
@arthursunbao  Please update to the latest onediff main branch. We have updated the performance just now: https://github.com/siliconflow/onediff/tree/main/onediff_sd_webui_extensions#performance-of-community-edition
