### ISSUE TITLE
DeepCache crashing

### ISSUE THREAD

**Issue by FilipAndersson245** [siliconflow/onediff#505]
### Describe the bug
Comfyui crashes when using the DeepCache node.

#### A clear and concise description of what the bug is.
It seem something is missing when trying to execute the DeepCache Node, oneflow otherwise seem to work fine.

#### OS 
```
                                                                                 
        a8888b.           Host        -  odin@valhalla                           
       d888888b.          Machine     -  ASUS System Product Name Version        
       8P"YP"Y88          Kernel      -  6.6.9-200.fc39.x86_64                   
       8|o||o|88          Distro      -  Fedora Linux 39 (Workstation Edition)   
       8'    .88          DE          -  GNOME                                   
       8`._.' Y8.         Packages    -  2426 (rpm), 37 (cargo)                  
      d/      `8b.        Terminal    -  kitty                                   
     dP        Y8b.       Shell       -  fish                                    
    d8:       ::88b.      Uptime      -  1h 7m                                   
   d8"         'Y88b      CPU         -  AMD Ryzen 9 7950X 16-Core Processor (32)
  :8P           :888      Resolution  -  2560x1440, 1920x1200                    
   8a.         _a88P      CPU Load    -  85%                                     
 ._/"Yaa     .| 88P|      Memory      -  4.2 GB/32.6 GB                          
 \    YP"    `|     `.                                                           
 /     \.___.d|    .'                                                            
 `--..__)     `._.'                                                              
```

#### OneDiff git commit id
`4b0761da3b87b7d531e36c92d4988547d2aa895f`

####  OneFlow version info
```
path: ['/home/odin/.pyenv/versions/comfyui_env/lib/python3.11/site-packages/oneflow']
version: 0.9.1.dev20240108+cu121
git_commit: c504292
cmake_build_type: Release
rdma: True
mlir: True
enterprise: False
```
Run `python -m oneflow --doctor` and paste it here.

### How To Reproduce
Steps to reproduce the behavior(code or script):
[workflow.json](https://github.com/siliconflow/onediff/files/13870876/workflow.json)

### The complete error message
```
RROR [2024-01-09 09:06:10] - Exception in __call__: e=AttributeError("'DeepCacheUNet' object has no attribute 'oneflow_module'")
  0%|                                                                                                                                                                                    | 0/20 [00:00<?, ?it/s]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/home/odin/dev/ai/onediff/src/onediff/infer_compiler/with_oneflow_compile.py", line 214, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odin/dev/ai/onediff/src/onediff/infer_compiler/with_oneflow_compile.py", line 188, in wrapper
    ret = func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odin/dev/ai/onediff/src/onediff/infer_compiler/with_oneflow_compile.py", line 294, in __call__
    dpl_graph = self.get_graph()
                ^^^^^^^^^^^^^^^^
  File "/home/odin/dev/ai/onediff/src/onediff/infer_compiler/with_oneflow_compile.py", line 266, in get_graph
    self._deployable_module_model.oneflow_module, size, all_dynamic
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odin/dev/ai/onediff/src/onediff/infer_compiler/with_oneflow_compile.py", line 84, in __getattr__
    torch_attr = getattr(self._torch_module, name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odin/.pyenv/versions/comfyui_env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'DeepCacheUNet' object has no attribute 'oneflow_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odin/dev/ai/ComfyUI/execution.py", line 154, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odin/dev/ai/ComfyUI/execution.py", line 84, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odin/dev/ai/ComfyUI/execution.py", line 77, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odin/dev/ai/ComfyUI/nodes.py", line 1299, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odin/dev/ai/ComfyUI/nodes.py", line 1269, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odin/dev/ai/ComfyUI/comfy/sample.py", line 101, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odin/dev/ai/ComfyUI/comfy/samplers.py", line 716, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odin/dev/ai/ComfyUI/comfy/samplers.py", line 622, in sample
    samples = sampler.sample(model_wrap, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odin/dev/ai/ComfyUI/comfy/samplers.py", line 561, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odin/.pyenv/versions/comfyui_env/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/odin/dev/ai/ComfyUI/comfy/k_diffusion/sampling.py", line 137, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odin/.pyenv/versions/comfyui_env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odin/.pyenv/versions/comfyui_env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odin/dev/ai/ComfyUI/comfy/samplers.py", line 285, in forward
    out = self.inner_model(x, sigma, cond=cond, uncond=uncond, cond_scale=cond_scale, model_options=model_options, seed=seed)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odin/.pyenv/versions/comfyui_env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odin/.pyenv/versions/comfyui_env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odin/dev/ai/ComfyUI/comfy/samplers.py", line 275, in forward
    return self.apply_model(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odin/dev/ai/ComfyUI/comfy/samplers.py", line 272, in apply_model
    out = sampling_function(self.inner_model, x, timestep, uncond, cond, cond_scale, model_options=model_options, seed=seed)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odin/dev/ai/ComfyUI/comfy/samplers.py", line 252, in sampling_function
    cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odin/dev/ai/ComfyUI/comfy/samplers.py", line 224, in calc_cond_uncond_batch
    output = model_options['model_function_wrapper'](model.apply_model, {"input": input_x, "timestep": timestep_, "c": c, "cond_or_uncond": cond_or_uncond}).chunk(batch_chunks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odin/dev/ai/ComfyUI/custom_nodes/onediff_comfy_nodes/_nodes.py", line 559, in apply_model
    model_output, cache_h = oneflow_model.deep_cache_unet(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odin/dev/ai/onediff/src/onediff/infer_compiler/utils/args_tree_util.py", line 34, in wrapper
    output = func(cls, *mapped_args, **mapped_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odin/dev/ai/onediff/src/onediff/infer_compiler/with_oneflow_compile.py", line 220, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odin/dev/ai/onediff/src/onediff/infer_compiler/with_oneflow_compile.py", line 188, in wrapper
    ret = func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odin/dev/ai/onediff/src/onediff/infer_compiler/with_oneflow_compile.py", line 294, in __call__
    dpl_graph = self.get_graph()
                ^^^^^^^^^^^^^^^^
  File "/home/odin/dev/ai/onediff/src/onediff/infer_compiler/with_oneflow_compile.py", line 266, in get_graph
    self._deployable_module_model.oneflow_module, size, all_dynamic
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odin/dev/ai/onediff/src/onediff/infer_compiler/with_oneflow_compile.py", line 84, in __getattr__
    torch_attr = getattr(self._torch_module, name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odin/.pyenv/versions/comfyui_env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'DeepCacheUNet' object has no attribute 'oneflow_module'
```

**Comment by strint** [comment]
> 'DeepCacheUNet' object has no attribute 'oneflow_module'

@clackhan

**Comment by clackhan** [comment]
You cannot provide accelerated nodes to Model DeepCache Speedup nodes. Just connect the normal node is fine, as the follow picture shown.
<img width="1022" alt="image" src="https://github.com/siliconflow/onediff/assets/28134523/ae7ad7de-bcae-4adc-a1f2-c1292dc0209f">

**Comment by FilipAndersson245** [comment]
Thanks that worked! :)
