### ISSUE TITLE
support for arbitrary input sizes

### ISSUE THREAD

**Issue by onefish51** [siliconflow/onediff#518]
Great job! I see that OneDiff can achieve support for multi-size inputs by loading precompiled static graphs. However, it seems that it still cannot achieve support for arbitrary input sizes, is that correct? thanks！

**Comment by hjchen2** [comment]
Normally, almost arbitrary input size is supported. It is convenient to tell me which workflow you are running and what the error message is?

**Comment by hjchen2** [comment]
Need to update to the latest onediff and oneflow. Last week we released the feature of supporting any dynamic input when loading the compiled graph for onediff community version.

**Comment by onefish51** [comment]
> Need to update to the latest onediff and oneflow. Last week we released the feature of supporting any dynamic input when loading the compiled graph for onediff community version.

well, I have a try!

**Comment by strint** [comment]
Instruction is here: https://github.com/siliconflow/onediff/releases/tag/0.12.0

@onefish51

**Comment by onefish51** [comment]
I see. I tried it out myself and encountered some difficulties with the environment setup. 
The first time, I used "docker pull pytorch/pytorch:2.1.1-cuda12.1-cudnn8-devel" ，and setup the environment
```bash
docker run --gpus all -it  -e CUDA_VISIBLE_DEVICES=2 pytorch/pytorch:2.1.1-cuda12.1-cudnn8-devel

pip install --pre oneflow -f https://oneflow-pro.oss-cn-beijing.aliyuncs.com/branch/community/cu121
python3 -m pip install "torch" "transformers==4.27.1" "diffusers[torch]==0.19.3"

git clone https://github.com/siliconflow/onediff.git

cd onediff && python3 -m pip install -e .

# Requirement already satisfied: oneflow in /opt/conda/lib/python3.10/site-packages (0.9.1.dev20240114+cu121)
# Requirement already satisfied: transformers>=4.27.1 in /opt/conda/lib/python3.10/site-packages (from onediff==0.12.1.dev0) (4.27.1)
# Requirement already satisfied: diffusers>=0.19.3 in /opt/conda/lib/python3.10/site-packages (from onediff==0.12.1.dev0) (0.19.3)
# Successfully installed onediff-0.12.1.dev0
```
But a bug was thrown:
```bash
Traceback (most recent call last):
  File "text2img_onediff.py", line 76, in <module>
    pipe.unet = oneflow_compile(pipe.unet)
  File "/app/onediff/src/onediff/infer_compiler/with_oneflow_compile.py", line 472, in oneflow_compile
    set_default_registry()
  File "/app/onediff/src/onediff/infer_compiler/transform/custom_transform.py", line 46, in set_default_registry
    import_module_from_path(registry_path / "register_diffusers")
  File "/app/onediff/src/onediff/infer_compiler/import_tools/importer.py", line 49, in import_module_from_path
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/onediff/src/infer_compiler_registry/register_diffusers/__init__.py", line 23, in <module>
    from .transformer_2d_oflow import Transformer2DModel as Transformer2DModelOflow
  File "/app/onediff/src/infer_compiler_registry/register_diffusers/transformer_2d_oflow.py", line 10, in <module>
    transformed_diffusers = transform_mgr.transform_package("diffusers")
  File "/app/onediff/src/onediff/infer_compiler/transform/manager.py", line 81, in transform_package
    return self._transform_entity(package_name)
  File "/app/onediff/src/onediff/infer_compiler/transform/manager.py", line 56, in _transform_entity
    result = self.mocker.mock_entity(entity)
  File "/app/onediff/src/onediff/infer_compiler/import_tools/importer.py", line 83, in mock_entity
    return self.load_entity_with_mock(entity)
  File "/app/onediff/src/onediff/infer_compiler/import_tools/importer.py", line 107, in load_entity_with_mock
    mock_pkg = DynamicMockModule.from_package(attrs[0], verbose=False)
  File "/opt/conda/lib/python3.10/site-packages/oneflow/mock_torch/dyn_mock_mod.py", line 65, in from_package
    obj_entity = importlib.import_module(main_pkg)
  File "/opt/conda/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/conda/lib/python3.10/site-packages/diffusers/__init__.py", line 3, in <module>
    from .configuration_utils import ConfigMixin
  File "/opt/conda/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 34, in <module>
    from .utils import (
  File "/opt/conda/lib/python3.10/site-packages/diffusers/utils/__init__.py", line 21, in <module>
    from .accelerate_utils import apply_forward_hook
  File "/opt/conda/lib/python3.10/site-packages/diffusers/utils/accelerate_utils.py", line 20, in <module>
    from .import_utils import is_accelerate_available
  File "/opt/conda/lib/python3.10/site-packages/diffusers/utils/import_utils.py", line 225, in <module>
    raise ValueError("PyTorch should be >= 1.12")
ValueError: PyTorch should be >= 1.12
```
but 
```bash
>>> import torch
>>> torch.__version__
'2.1.1'
```
And the second time, I used "docker pull" directly.

```bash
docker pull oneflowinc/onediff:cu118
docker run --gpus all -it -e CUDA_VISIBLE_DEVICES=0 oneflowinc/onediff:cu118
python text2img_onediff.py
```
This time the code ran without any errors, but the execution time was significantly incorrect. It was more than four times longer than the old version of OneDiff (0.11.4).

```bash
$ python text2img_onediff.py
Ignoring PCI device with non-16bit domain.
Pass --enable-32bits-pci-domain to configure to support such devices
(warning: it would break the library ABI, don't enable unless really needed).
Loading pipeline components...: 100%|████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.74it/s]
Warming up for standard
  0%|                                                                                                                               | 0/30 [00:00<?, ?it/s]W20240115 08:29:34.887506   588 cuda_stream.cpp:49] Runtime version 11.10 of cuBLAS incompatible with compiletime version 11.11.
W20240115 08:29:35.012981   588 cuda_stream.cpp:49] Runtime version 8.4 of cuDNN incompatible with compiletime version 8.9.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:24<00:00,  1.21it/s]
run 512 cost 25.35175395011902
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:10<00:00,  2.78it/s]
run 640 cost 10.940327882766724
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:13<00:00,  2.26it/s]
run 768 cost 13.456756830215454
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:16<00:00,  1.80it/s]
run 1024 cost 17.027422189712524
```
and I check the env
```bash
>>> import torch
>>> torch.__version__
'2.1.0a0+29c30b1'
>>> torch.cuda.is_available()
True

$ nvidia-smi
Mon Jan 15 08:26:44 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.29.06              Driver Version: 545.29.06    CUDA Version: 12.3     |
```

**Comment by strint** [comment]
> PyTorch should be >= 1.12

@ccssu seems an old error that has been fixed before？

**Comment by onefish51** [comment]
I build it again ,this time it succeed .
I used "docker pull pytorch/pytorch:2.1.1-cuda12.1-cudnn8-devel" ，and setup the environment
```bash
docker run --gpus all -it  -e CUDA_VISIBLE_DEVICES=2 pytorch/pytorch:2.1.1-cuda12.1-cudnn8-devel

pip install --pre oneflow -f https://oneflow-pro.oss-cn-beijing.aliyuncs.com/branch/community/cu121
python3 -m pip install "torch" "transformers==4.27.1" "diffusers[torch]==0.19.3"

git clone https://github.com/siliconflow/onediff.git

cd onediff && python3 -m pip install -e .

# Successfully installed markdown-it-py-3.0.0 mdurl-0.1.2 oneflow-0.9.1.dev20240115+cu121 protobuf-3.20.3 rich-13.7.0
# Successfully installed onediff-0.12.1.dev0
```
but when I tested `text2img_onediff_multi_size.py`
```python
import argparse

import oneflow as flow
import torch

from onediff.infer_compiler import oneflow_compile
from onediff.infer_compiler.utils.cost_util import cost_cnt
from onediff.schedulers import EulerDiscreteScheduler
from onediff.optimization import rewrite_self_attention
from diffusers import StableDiffusionXLPipeline
import time

parser = argparse.ArgumentParser()
parser.add_argument(
    "--base", type=str, default="/data2/home/tyu/stable_diffusion/diffusers/models/stable-diffusion-xl-base-1.0"
)
parser.add_argument("--variant", type=str, default="fp16")
parser.add_argument(
    "--prompt",
    type=str,
    default="street style, detailed, raw photo, woman, face, shot on CineStill 800T",
)
parser.add_argument("--height", type=int, default=1280)
parser.add_argument("--width", type=int, default=1280)
parser.add_argument("--n_steps", type=int, default=2)
parser.add_argument("--saved_image", type=str, required=False, default="sdxl-out.png")
parser.add_argument("--warmup", type=int, default=1)
parser.add_argument("--seed", type=int, default=1)
parser.add_argument(
    "--compile", type=(lambda x: str(x).lower() in ["true", "1", "yes"]), default=True
)
args = parser.parse_args()

# Normal SDXL pipeline init.
output_type = "pil"

# SDXL base: StableDiffusionXLPipeline
scheduler = EulerDiscreteScheduler.from_pretrained(args.base, subfolder="scheduler")
base = StableDiffusionXLPipeline.from_pretrained(
    args.base,
    scheduler=scheduler,
    torch_dtype=torch.float16,
    variant=args.variant,
    use_safetensors=True,
)
base.to("cuda")

# Compile unet with oneflow
if args.compile:
    print("unet is compiled to oneflow.")
    rewrite_self_attention(base.unet)
    # base.unet = oneflow_compile(base.unet)
    base.unet = oneflow_compile(
                        base.unet, options={"size": 4}
                    )

# @cost_cnt
def run_once(args, h, w, i, output_type):
    start = time.time()
    print(f"====> run {i}-th h {h} w {w}")
    image = base(
        prompt=args.prompt,
        height=h,
        width=w,
        num_inference_steps=args.n_steps,
        output_type=output_type,
    ).images
    # torch.cuda.empty_cache()
    end = time.time()
    print(f'infer one cost { end - start}')
# Normal SDXL run
torch.manual_seed(args.seed)
# sizes = [1280, 1200, 1120, 960, 840, 800, 720]
sizes = [960, 720]
# @cost_cnt
def test_49_graph():
    for h in sizes:
        for w in sizes:
            for i in range(2):
                run_once(args, h, w, i, output_type)
    # empty torch mem cache
    torch.cuda.empty_cache()

test_49_graph()
```
the output shown any dynamic input do not support:
```bash
Loading pipeline components...: 100%|████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:01<00:00,  5.56it/s]
unet is compiled to oneflow.
====> run 0-th h 960 w 960
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [01:27<00:00, 43.59s/it]
infer one cost 88.84186935424805
====> run 1-th h 960 w 960
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  7.69it/s]
infer one cost 0.6987709999084473
====> run 0-th h 960 w 720
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:17<00:00,  8.63s/it]
infer one cost 17.600704193115234
====> run 1-th h 960 w 720
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  9.53it/s]
infer one cost 0.550666332244873
====> run 0-th h 720 w 960
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:16<00:00,  8.26s/it]
infer one cost 16.864193439483643
====> run 1-th h 720 w 960
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  9.59it/s]
infer one cost 0.5499904155731201
====> run 0-th h 720 w 720
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:14<00:00,  7.46s/it]
infer one cost 15.19884443283081
====> run 1-th h 720 w 720
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 11.89it/s]
infer one cost 0.44790220260620117
```

**Comment by strint** [comment]
> I build it again ,this time it succeed .  I used "docker pull pytorch/pytorch:2.1.1-cuda12.1-cudnn8-devel" ，and setup the environment

Great job! @onefish51

**Comment by onefish51** [comment]
> Need to update to the latest onediff and oneflow. Last week we released the feature of supporting any dynamic input when loading the compiled graph for onediff community version.

However, the functionality for arbitrary input sizes did not work as expected. Is there a different invocation mode for this feature?

**Comment by strint** [comment]
@onefish51 We found a bug yesterday with the dynamic shape. The first graph is not run with the dynamic shape.

Please use this branch: https://github.com/siliconflow/onediff/pull/525

And it's should be fixed.

**Comment by onefish51** [comment]
Great job! I just tested it by `https://github.com/siliconflow/onediff/blob/main/examples/text_to_image_sdxl.py` and overall it works. 
However, I encountered an issue: 

Firstly,  if there is a change in the input size from [896, 768] to [960, 720], an error occurs.
```bash
python text_to_image_sdxl.py 
libibverbs not available, ibv_fork_init skipped
Ignoring PCI device with non-16bit domain.
Pass --enable-32bits-pci-domain to configure to support such devices
(warning: it would break the library ABI, don't enable unless really needed).
Loading pipeline components...: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00,  9.64it/s]
Compiling unet with oneflow.
Compiling vae with oneflow.
Warmup with running graphs...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:56<00:00,  1.87s/it]
W20240117 07:49:12.241235   973 cudnn_conv_util.cpp:105] Currently available alogrithm (algo=0, require memory=0, idx=1) meeting requirments (max_workspace_size=2147483648, determinism=0) is not fastest. Fastest algorithm (1) requires memory 2149842960
Warmup cost 59.32852792739868
Normal SDXL run...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:04<00:00,  7.45it/s]
Normal cost 4.5491204261779785
Warmup run with multiple resolutions...
====> run h 960 w 960
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:03<00:00,  7.88it/s]
infer one cost 4.2422120571136475
====> run h 960 w 720
  0%|                                                                                                                                                                          | 0/30 [00:00<?, ?it/s][ERROR](GRAPH:OneflowGraph_0:OneflowGraph) run got error: <class 'oneflow._oneflow_internal.exception.Exception'> Check failed: (45 == 46) 
  File "oneflow/core/job/job_interpreter.cpp", line 307, in InterpretJob
    RunNormalOp(launch_context, launch_op, inputs)
  File "oneflow/core/job/job_interpreter.cpp", line 219, in RunNormalOp
    it.Apply(*op, inputs, &outputs, OpExprInterpContext(empty_attr_map, JUST(launch_op.device)))
  File "oneflow/core/framework/op_interpreter/eager_local_op_interpreter.cpp", line 84, in NaiveInterpret
    [&]() -> Maybe<const LocalTensorInferResult> { LocalTensorMetaInferArgs ... mut_local_tensor_infer_cache()->GetOrInfer(infer_args)); }()
  File "oneflow/core/framework/op_interpreter/eager_local_op_interpreter.cpp", line 87, in operator()
    user_op_expr.mut_local_tensor_infer_cache()->GetOrInfer(infer_args)
  File "oneflow/core/framework/local_tensor_infer_cache.cpp", line 210, in GetOrInfer
    Infer(*user_op_expr, infer_args)
  File "oneflow/core/framework/local_tensor_infer_cache.cpp", line 178, in Infer
    user_op_expr.InferPhysicalTensorDesc( infer_args.attrs ... ) -> TensorMeta* { return &output_mut_metas.at(i); })
  File "oneflow/core/framework/op_expr.cpp", line 602, in InferPhysicalTensorDesc
    physical_tensor_desc_infer_fn_(&infer_ctx)
  File "oneflow/user/ops/concat_op.cpp", line 55, in InferLogicalTensorDesc
    CHECK_EQ_OR_RETURN(in_desc.shape().At(i), out_dim_vec.at(i))
Error Type: oneflow.ErrorProto.check_failed_error
ERROR [2024-01-17 07:49:22] - Exception in __call__: e=Exception('Check failed: (45 == 46) \n  File "oneflow/core/job/job_interpreter.cpp", line 307, in InterpretJob\n    RunNormalOp(launch_context, launch_op, inputs)\n  File "oneflow/core/job/job_interpreter.cpp", line 219, in RunNormalOp\n    it.Apply(*op, inputs, &outputs, OpExprInterpContext(empty_attr_map, JUST(launch_op.device)))\n  File "oneflow/core/framework/op_interpreter/eager_local_op_interpreter.cpp", line 84, in NaiveInterpret\n    [&]() -> Maybe<const LocalTensorInferResult> { LocalTensorMetaInferArgs ... mut_local_tensor_infer_cache()->GetOrInfer(infer_args)); }()\n  File "oneflow/core/framework/op_interpreter/eager_local_op_interpreter.cpp", line 87, in operator()\n    user_op_expr.mut_local_tensor_infer_cache()->GetOrInfer(infer_args)\n  File "oneflow/core/framework/local_tensor_infer_cache.cpp", line 210, in GetOrInfer\n    Infer(*user_op_expr, infer_args)\n  File "oneflow/core/framework/local_tensor_infer_cache.cpp", line 178, in Infer\n    user_op_expr.InferPhysicalTensorDesc( infer_args.attrs ... ) -> TensorMeta* { return &output_mut_metas.at(i); })\n  File "oneflow/core/framework/op_expr.cpp", line 602, in InferPhysicalTensorDesc\n    physical_tensor_desc_infer_fn_(&infer_ctx)\n  File "oneflow/user/ops/concat_op.cpp", line 55, in InferLogicalTensorDesc\n    CHECK_EQ_OR_RETURN(in_desc.shape().At(i), out_dim_vec.at(i))\nError Type: oneflow.ErrorProto.check_failed_error')
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:43<00:00,  1.45s/it]
infer one cost 43.735071659088135

....
```

**Comment by strint** [comment]
> AttributeError: 'Decoder' object has no attribute 'save_graph'

Please change
```
# Compile vae with oneflow
if cmd_args.compile_vae:
    print("Compiling vae with oneflow.")
    base.vae = oneflow_compile(base.vae)
```
to 
```
# Compile vae with oneflow
if cmd_args.compile_vae:
    print("Compiling vae with oneflow.")
    base.vae.decoder = oneflow_compile(base.vae.decoder)
```

**Comment by strint** [comment]
> if there is a change in the input size from [896, 768] to [960, 720], an error occurs.

Thanks, please create a new issue for this. @onefish51

**Comment by onefish51** [comment]
> `https://github.com/siliconflow/onediff/blob/main/examples/text_to_image_sdxl.py` and overall it works. However, I encountered a few issues:
> 
> Firstly, if there is a change in the input size from [896, 768] to [960, 720], an error occurs.

yes ! I got it! You're amazing! besides how to save `vae.encoder` for img2img?

**Comment by strint** [comment]
> > `https://github.com/siliconflow/onediff/blob/main/examples/text_to_image_sdxl.py` and overall it works. However, I encountered a few issues:
> > Firstly, if there is a change in the input size from [896, 768] to [960, 720], an error occurs.
> 
> yes ! I got it! You're amazing! besides how to save `vae.encoder` for img2img?

Any error while saving the graph of vae.encoder?

**Comment by onefish51** [comment]
when run `    base.vae.encoder.save_graph("base_vae_encoder_compiled")` 

an error was thrown:

```bash
Traceback (most recent call last):
  File "examples/text2img_onediff_save_load.py", line 134, in <module>
    base.vae.encoder.save_graph("base_vae_encoder_compiled")
  File "/app/onediff/src/onediff/infer_compiler/with_oneflow_compile.py", line 312, in save_graph
    self.get_graph().save_graph(file_path)
  File "/app/onediff/src/onediff/infer_compiler/utils/cost_util.py", line 46, in clocked
    return func(*args, **kwargs)
  File "/app/onediff/src/onediff/infer_compiler/with_oneflow_compile.py", line 360, in save_graph
    state_dict = self.runtime_state_dict()
  File "/opt/conda/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 1076, in runtime_state_dict
    return self._dynamic_input_graph_cache.runtime_state_dict(
  File "/opt/conda/lib/python3.10/site-packages/oneflow/nn/graph/cache.py", line 130, in runtime_state_dict
    for (key, graph) in self._cache.items():
AttributeError: 'NoneType' object has no attribute 'items'
```

**Comment by strint** [comment]
>     for (key, graph) in self._cache.items():
> AttributeError: 'NoneType' object has no attribute 'items'
> ```

It seems that  `vae.encoder` has never been called in your pipeline？ So cannot be saved.

**Comment by onefish51** [comment]
ah ha !  I see!
