### ISSUE TITLE
onediff-0.12.0: Error: This runtime mode is not supported in community version, please upgrade oneflow to the enterprise version.

### ISSUE THREAD

**Issue by HydrogenQAQ** [siliconflow/onediff#543]
#### A clear and concise description of what the bug is.

The script that can be run in version 0.11.4, currently reports the following error in version 0.12.0(Multiple Resolutions):

```
DEBUG [2024-01-19 10:27:55] - Updated class proxies: len(class_proxy_dict)=1
{'diffusers.models.attention_processor.Attention': <class 'register_diffusers.attention_processor_oflow.Attention'>}

DEBUG [2024-01-19 10:27:55] - Updated class proxies: len(class_proxy_dict)=1
{'diffusers.models.attention_processor.AttnProcessor2_0': <class 'register_diffusers.attention_processor_oflow.AttnProcessor'>}

DEBUG [2024-01-19 10:27:55] - Updated class proxies: len(class_proxy_dict)=1
{'diffusers.models.attention_processor.LoRAAttnProcessor2_0': <class 'register_diffusers.attention_processor_oflow.LoRAAttnProcessor2_0'>}

DEBUG [2024-01-19 10:27:55] - Updated class proxies: len(class_proxy_dict)=1
{'diffusers.models.resnet.SpatioTemporalResBlock': <class 'register_diffusers.spatio_temporal_oflow.SpatioTemporalResBlock'>}

DEBUG [2024-01-19 10:27:55] - Updated class proxies: len(class_proxy_dict)=1
{'diffusers.models.autoencoder_kl_temporal_decoder.TemporalDecoder': <class 'register_diffusers.spatio_temporal_oflow.TemporalDecoder'>}

DEBUG [2024-01-19 10:27:55] - Updated class proxies: len(class_proxy_dict)=1
{'diffusers.models.transformer_2d.Transformer2DModel': <class 'register_diffusers.transformer_2d_oflow.Transformer2DModel'>}

INFO [2024-01-19 10:27:55] - Failed to register_onediff_quant e=ModuleNotFoundError("No module named 'onediff_quant'")
INFO [2024-01-19 10:27:55] - Failed to register_diffusers_enterprise_lite e=ModuleNotFoundError("No module named 'diffusers_enterprise_lite'")
/root/workspace/diffusers_v2/src/diffusers/pipelines/stable_diffusion/util.py:33: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  result = torch.tensor(result)
DEBUG [2024-01-19 10:27:57] - Convert <class 'diffusers.models.vae.Encoder'> ...
INFO [2024-01-19 10:27:58] - instance_name: AttnProcessor2_0 transformed to  <class 'register_diffusers.attention_processor_oflow.AttnProcessor'>
DEBUG [2024-01-19 10:27:58] - Convert id(self._torch_module)=140285655078016 done!
(GRAPH:OneflowGraph_0:OneflowGraph) got a new input shape, is compiling a new graph.
(GRAPH:OneflowGraph_0:OneflowGraph) is creating a graph cache with key 9049530011567247245.
(GRAPH:OneflowGraph_0:OneflowGraph) start building graph.
(GRAPH:OneflowGraph_0:OneflowGraph) building graph Done! Cost time: 16.31s.

(GRAPH:OneflowGraph_0:OneflowGraph) start building runtime.
(GRAPH:OneflowGraph_0:OneflowGraph) building runtime Done! Cost time: 0.15s.

[ERROR](GRAPH:OneflowGraph_0:OneflowGraph) run got error: <class 'oneflow._oneflow_internal.exception.NotImplementedError'> Error: This runtime mode is not supported in community version, please upgrade oneflow to the enterprise version.

Traceback (most recent call last):
  ...
  File "/root/workspace/diffusers_v2/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py", line 1038, in __call__
    latents = self.prepare_latents(
  File "/root/workspace/diffusers_v2/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py", line 652, in prepare_latents
    init_latents = retrieve_latents(self.vae.encode(image), generator=generator)
  File "/root/workspace/diffusers_v2/src/diffusers/utils/accelerate_utils.py", line 46, in wrapper
    return method(self, *args, **kwargs)
  File "/root/workspace/diffusers_v2/src/diffusers/models/autoencoder_kl.py", line 259, in encode
    h = self.encoder(x)
  File "/root/workspace/onediff/src/onediff/infer_compiler/utils/args_tree_util.py", line 34, in wrapper
    output = func(cls, *mapped_args, **mapped_kwargs)
  File "/root/workspace/onediff/src/onediff/infer_compiler/with_oneflow_compile.py", line 169, in wrapper
    return func(self, *args, **kwargs)
  File "/root/workspace/onediff/src/onediff/infer_compiler/utils/graph_management_utils.py", line 69, in wrapper
    ret = func(self, *args, **kwargs)
  File "/root/workspace/onediff/src/onediff/infer_compiler/with_oneflow_compile.py", line 257, in __call__
    output = dpl_graph(*args, **kwargs)
  File "/root/software/anaconda3/envs/onediff/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 297, in __call__
    return self.__run(*args, **kwargs)
  File "/root/software/anaconda3/envs/onediff/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 1857, in __run
    _eager_outputs = oneflow._oneflow_internal.nn.graph.RunLazyNNGraphByVM(
oneflow._oneflow_internal.exception.NotImplementedError: Error: This runtime mode is not supported in community version, please upgrade oneflow to the enterprise version.
```

#### OS 
cuda 12.1, torch 2.1.1, diffusers 0.24.0, oneflow 0.9.1

#### OneDiff git commit id
onediff-0.12.0
1654c8682172ee71d18ca4af9f7f7af48a4787b9

####  OneFlow version info
Run `python -m oneflow --doctor` and paste it here.

```
version: 0.9.1.dev20240108+cu121
git_commit: c504292
cmake_build_type: Release
rdma: True
mlir: True
enterprise: False

```
### How To Reproduce
Steps to reproduce the behavior(code or script):

**Comment by strint** [comment]
> OneFlow version info
> git_commit: c504292

this is a pretty old oneflow version.(2 weeks ago)

please uninstall oneflow and update to the most recent oneflow with: https://github.com/siliconflow/onediff?tab=readme-ov-file#1-install-oneflow

**Comment by strint** [comment]
#555 shows this error is fixed. So close here.

Feel free to reopen it if the error still exists.
