### ISSUE TITLE
测试文生图例子报错 'MixedDualModule' object has no attribute '_oneflow_module'

### ISSUE THREAD

**Issue by Bluewind001** [siliconflow/onediff#577]
#### A clear and concise description of what the bug is.
下载安装，运行`python3 examples/text_to_image.py` 报错
``` 
Traceback (most recent call last):
  File "examples/text_to_image.py", line 47, in <module>
    pipe.unet = oneflow_compile(pipe.unet)
  File "/opt/conda/lib/python3.8/site-packages/onediff/infer_compiler/with_oneflow_compile.py", line 460, in oneflow_compile
    model = wrap_module(torch_module)
  File "/opt/conda/lib/python3.8/site-packages/onediff/infer_compiler/with_oneflow_compile.py", line 456, in wrap_module
    return get_mixed_deployable_module(module.__class__)(
  File "/opt/conda/lib/python3.8/site-packages/onediff/infer_compiler/with_oneflow_compile.py", line 401, in __init__
    DeployableModule.__init__(
  File "/opt/conda/lib/python3.8/site-packages/onediff/infer_compiler/with_oneflow_compile.py", line 195, in __init__
    self._deployable_module_model = get_mixed_dual_module(torch_module.__class__)(
  File "/opt/conda/lib/python3.8/site-packages/onediff/infer_compiler/with_oneflow_compile.py", line 160, in __init__
    DualModule.__init__(self, torch_module, oneflow_module)
  File "/opt/conda/lib/python3.8/site-packages/onediff/infer_compiler/with_oneflow_compile.py", line 22, in __init__
    torch.nn.Module.__init__(self)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 260, in __init__
    self.training = True
  File "/opt/conda/lib/python3.8/site-packages/onediff/infer_compiler/with_oneflow_compile.py", line 109, in __setattr__
    if self._oneflow_module is not None:
  File "/opt/conda/lib/python3.8/site-packages/onediff/infer_compiler/with_oneflow_compile.py", line 86, in __getattr__
    return super().__getattribute__(name)
AttributeError: 'MixedDualModule' object has no attribute '_oneflow_module'
```

### Your environment
Linux
python 3.8.5
onediff                          0.12.1.dev202401260125
oneflow                          0.9.1.dev20240125+cu118

**Comment by strint** [comment]
python -c "import torch; print(torch.__version__)"

please use this to get the pytorch version here

**Comment by strint** [comment]
I can reproduce your problem, but you can also take a try:
https://github.com/siliconflow/onediff/blob/main/src/onediff/infer_compiler/with_oneflow_compile.py#L20
change 
```
class DualModule(torch.nn.Module):
    def __init__(self, torch_module, oneflow_module):
        torch.nn.Module.__init__(self)
        self._torch_module = torch_module
        self._oneflow_module = oneflow_module
```
to 
```
class DualModule(torch.nn.Module):
    def __init__(self, torch_module, oneflow_module):
        self._torch_module = torch_module
        self._oneflow_module = oneflow_module
        torch.nn.Module.__init__(self)
```

**Comment by hjchen2** [comment]
https://github.com/siliconflow/onediff/blob/main/src/onediff/infer_compiler/with_oneflow_compile.py#L109

Maybe you can try change the line 109 from
```python
if self._oneflow_module is not None:
```
to 
```python
if hasattr(self, '_oneflow_module') and self._oneflow_module is not None:
```

**Comment by Bluewind001** [comment]
@strint    my pytorch version `1.11.0+cu113`

我尝试用了
```
class DualModule(torch.nn.Module):
    def __init__(self, torch_module, oneflow_module):
        self._torch_module = torch_module
        self._oneflow_module = oneflow_module
        torch.nn.Module.__init__(self)
```
这个方法，  报错
```
Traceback (most recent call last):
  File "examples/text_to_image.py", line 47, in <module>
    pipe.unet = oneflow_compile(pipe.unet)
  File "/face_project/onediff-main/src/onediff/infer_compiler/with_oneflow_compile.py", line 467, in oneflow_compile
    model = wrap_module(torch_module)
  File "/face_project/onediff-main/src/onediff/infer_compiler/with_oneflow_compile.py", line 463, in wrap_module
    return get_mixed_deployable_module(module.__class__)(
  File "/face_project/onediff-main/src/onediff/infer_compiler/with_oneflow_compile.py", line 408, in __init__
    DeployableModule.__init__(
  File "/face_project/onediff-main/src/onediff/infer_compiler/with_oneflow_compile.py", line 202, in __init__
    self._deployable_module_model = get_mixed_dual_module(torch_module.__class__)(
  File "/face_project/onediff-main/src/onediff/infer_compiler/with_oneflow_compile.py", line 167, in __init__
    DualModule.__init__(self, torch_module, oneflow_module)
  File "/face_project/onediff-main/src/onediff/infer_compiler/with_oneflow_compile.py", line 28, in __init__
    self._torch_module = torch_module
  File "/face_project/onediff-main/src/onediff/infer_compiler/with_oneflow_compile.py", line 113, in __setattr__
    super().__setattr__(name, value)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1214, in __setattr__
    raise AttributeError(
AttributeError: cannot assign module before Module.__init__() call
```

**Comment by Bluewind001** [comment]
@hjchen2   我尝试改了109行，`if hasattr(self, '_oneflow_module') and self._oneflow_module is not None:`
但是也报错了
```
Traceback (most recent call last):
  File "examples/text_to_image.py", line 47, in <module>
    pipe.unet = oneflow_compile(pipe.unet)
  File "/face_project/onediff-main/src/onediff/infer_compiler/with_oneflow_compile.py", line 467, in oneflow_compile
    model = wrap_module(torch_module)
  File "/face_project/onediff-main/src/onediff/infer_compiler/with_oneflow_compile.py", line 463, in wrap_module
    return get_mixed_deployable_module(module.__class__)(
  File "/face_project/onediff-main/src/onediff/infer_compiler/with_oneflow_compile.py", line 408, in __init__
    DeployableModule.__init__(
  File "/face_project/onediff-main/src/onediff/infer_compiler/with_oneflow_compile.py", line 202, in __init__
    self._deployable_module_model = get_mixed_dual_module(torch_module.__class__)(
  File "/face_project/onediff-main/src/onediff/infer_compiler/with_oneflow_compile.py", line 167, in __init__
    DualModule.__init__(self, torch_module, oneflow_module)
  File "/face_project/onediff-main/src/onediff/infer_compiler/with_oneflow_compile.py", line 22, in __init__
    torch.nn.Module.__init__(self)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 260, in __init__
    self.training = True
  File "/face_project/onediff-main/src/onediff/infer_compiler/with_oneflow_compile.py", line 123, in __setattr__
    setattr(self._torch_module, name, value)
  File "/face_project/onediff-main/src/onediff/infer_compiler/with_oneflow_compile.py", line 90, in __getattr__
    return self._modules[name]
  File "/face_project/onediff-main/src/onediff/infer_compiler/with_oneflow_compile.py", line 94, in __getattr__
    torch_attr = getattr(self._torch_module, name)
... 这中间都是重复上面2行的错误...
RecursionError: maximum recursion depth exceeded in comparison
```

**Comment by hjchen2** [comment]
先将torch更新到1.14或以上版本，应该可以解决您的问题，1.11版本我们目前没有验证过。

**Comment by Bluewind001** [comment]
@hjchen2   感谢，把torch升级到2.0之后就没有问题了。

**Comment by bigmover** [comment]
> 先将torch更新到1.14或以上版本，应该可以解决您的问题，1.11版本我们目前没有验证过。 

@hjchen2 请问现在也是支持 1.13及以上版本吗？使用onediff 出现了一个报错：
File \"/home/admin/miniconda3/lib/python3.9/site-packages/transformers/modeling_utils.py\", line 1044, in device\\n    return get_parameter_device(self)\\n', '  File \"/home/admin/miniconda3/lib/python3.9/site-packages/transformers/modeling_utils.py\", line 225, in get_parameter_device\\n    first_tuple = next(gen)\\n', 'StopIteration\\n']
有遇见过类似的case吗？
