### ISSUE TITLE
TypeError: StableVideoDiffusionPipeline.__call__() got an unexpected keyword argument 'cache_layer_id'

### ISSUE THREAD

**Issue by onefish51** [siliconflow/onediff#607]
### Describe the bug
Run [Stable Video Diffusion with OneDiffX](https://github.com/siliconflow/onediff/tree/main/onediff_diffusers_extensions#run-stable-video-diffusion-with-onediffx) an error thrown

### Your environment
```bash
Ubuntu 18.04.6 LTS (GNU/Linux 5.4.0-150-generic x86_64)
```
#### OneDiff git commit id
```bash
Successfully installed onediff-0.12.1.dev1
```
####  OneFlow version info
```bash
libibverbs not available, ibv_fork_init skipped
Ignoring PCI device with non-16bit domain.
Pass --enable-32bits-pci-domain to configure to support such devices
(warning: it would break the library ABI, don't enable unless really needed).
path: ['/opt/conda/lib/python3.10/site-packages/oneflow']
version: 0.9.1.dev20240125+cu121
git_commit: 6458a12
cmake_build_type: Release
rdma: True
mlir: True
enterprise: False
```
### How To Reproduce
```python
import torch

from diffusers.utils import load_image, export_to_video
from onediffx import compile_pipe, compiler_config
from onediffx.deep_cache import StableVideoDiffusionPipeline

pipe = StableVideoDiffusionPipeline.from_pretrained(
    "stabilityai/stable-video-diffusion-img2vid-xt",
    torch_dtype=torch.float16,
    variant="fp16",
    use_safetensors=True
)
pipe.to("cuda")

compiler_config.attention_allow_half_precision_score_accumulation_max_m = 0
pipe = compile_pipe(pipe)

input_image = load_image("https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/diffusers/svd/rocket.png?download=true")
input_image = input_image.resize((1024, 576))

# Warmup
for i in range(1):
    deepcache_output = pipe(
        input_image, 
        decode_chunk_size=5,
        cache_interval=3, cache_layer_id=0, cache_block_id=0,
    ).frames[0]

deepcache_output = pipe(
    input_image, 
    decode_chunk_size=5,
    cache_interval=3, cache_layer_id=0, cache_block_id=0,
).frames[0]

export_to_video(deepcache_output, "generated.mp4", fps=7)
```

### The complete error message
```bash
libibverbs not available, ibv_fork_init skipped
Ignoring PCI device with non-16bit domain.
Pass --enable-32bits-pci-domain to configure to support such devices
(warning: it would break the library ABI, don't enable unless really needed).
In our loading pipeline
Loading pipeline components...: 100%|██████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00,  7.60it/s]
Compiling image_encoder
Compiling unet
Compiling fast_unet
Compiling vae.decoder
Compiling vae.encoder
Patching image_processor
Traceback (most recent call last):
  File "svd_deepcache_onediff2.py", line 23, in <module>
    deepcache_output = pipe(
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
TypeError: StableVideoDiffusionPipeline.__call__() got an unexpected keyword argument 'cache_layer_id'
```

**Comment by clackhan** [comment]
for SVD-deepcache，you should give the arg cache_branch, instead of cache_layer_id and cache_block_id，you should give the arg and cache_branch, instead of cache_layer_id and cache_block_id.
please reference https://github.com/siliconflow/onediff/blob/main/benchmarks/image_to_video.py

**Comment by strint** [comment]
doc problem: https://github.com/siliconflow/onediff/tree/main/onediff_diffusers_extensions#run-stable-diffusion-15-with-onediffx

**Comment by onefish51** [comment]
> for SVD-deepcache，you should give the arg cache_branch, instead of cache_layer_id and cache_block_id. please reference https://github.com/siliconflow/onediff/blob/main/benchmarks/image_to_video.py

Actually, I made the parameter changes as you suggested, but the generated results have issues. 

Code: 
```python
scheduler = EulerDiscreteScheduler.from_pretrained(args.base, subfolder="scheduler")
base = StableVideoDiffusionPipeline.from_pretrained(
    args.base,
    scheduler=scheduler,
    torch_dtype=torch.float16,
    # safety_checker=None,
    variant=args.variant,
    use_safetensors=True,
)
base.to("cuda")

# Compile unet with oneflow
if args.compile:
    print("Compiling unet with oneflow.")
    # base.unet = oneflow_compile(base.unet)
    # base.fast_unet = oneflow_compile(base.fast_unet)
    # base.vae.decoder = oneflow_compile(base.vae.decoder)
    # base = oneflow_compile(base)
    compiler_config.attention_allow_half_precision_score_accumulation_max_m = 0
    # base = compile_pipe(base)
    base = compile_pipe(base,)

# Adjust size to be divisible by 32


f = lambda : base(
    input_image, 
    decode_chunk_size=5,
    # prompt=args.prompt,
    height=h,
    width=w,
    num_inference_steps=args.n_steps,
    # output_type=OUTPUT_TYPE,
    cache_interval=3, 
    cache_branch=0, 
    # cache_block_id=0,
).frames[0]


print("Warmup")
for i in range(args.warmup):
    start = time.time()
    f()
    print(f'Warmup cost { time.time() - start}')

generator = torch.manual_seed(42)
# Normal SDXL run
# torch.manual_seed(args.seed)
start = time.time()
deepcache_output = base(
    input_image, 
    decode_chunk_size=5, 
    generator=generator, 
    num_frames=25, 
    motion_bucket_id=180, 
    noise_aug_strength=0.1,
    height=h,
    width=w,
    num_inference_steps=args.n_steps,
    cache_interval=3,
    cache_branch=0,
    # cache_block_id=0,
).frames[0]
print(f'run cost { time.time() - start}')
# image[0].save(f"h{args.height}-w{args.width}-{args.saved_image}")
export_to_video(deepcache_output, "generated_deepcache.mp4", fps=7)
```
Results:
https://github.com/siliconflow/onediff/assets/21029719/b3148ab8-ffae-484e-943d-e5599d2dd1cb

**Comment by strint** [comment]
@onefish51  does this problem still exist?

**Comment by onefish51** [comment]
yes ! fixed!
