### ISSUE TITLE
deepcache compatiable for  hf diffusres 0.26

### ISSUE THREAD

**Issue by strint** [siliconflow/onediff#636]
#### A clear and concise description of what the bug is.
```
WARNING [2024-02-07 05:[15](https://github.com/siliconflow/onediff/actions/runs/7810062569/job/21302887535?pr=634#step:29:16):45] manager.py:96 - Pydantic version 1.10.12 is too low, please upgrade to 2.5.2 or higher.
Traceback (most recent call last):
  File "/src/onediff/examples/text_to_image_deep_cache_sdxl_enterprise.py", line 64, in <module>
    from onediffx.deep_cache import StableDiffusionXLPipeline
  File "/src/onediff/onediff_diffusers_extensions/onediffx/deep_cache/__init__.py", line 3, in <module>
    from .pipeline_stable_diffusion_xl import StableDiffusionXLPipeline
  File "/src/onediff/onediff_diffusers_extensions/onediffx/deep_cache/pipeline_stable_diffusion_xl.py", line 53, in <module>
    from .models.unet_2d_condition import UNet2DConditionModel
  File "/src/onediff/onediff_diffusers_extensions/onediffx/deep_cache/models/unet_2d_condition.py", line 32, in <module>
    from diffusers.models.embeddings import (
ImportError: cannot import name 'PositionNet' from 'diffusers.models.embeddings' (/usr/local/lib/python3.10/dist-packages/diffusers/models/embeddings.py)
```
PositionNet is renamed in diffusers 0.26:
https://github.com/huggingface/diffusers/pull/6244

#### OneDiff git commit id
4da2270a51100ad7cd71c6468b0e46298319b978

####  OneFlow version info
Run `python -m oneflow --doctor` and paste it here.

### How To Reproduce
Steps to reproduce the behavior(code or script):

```
python3 examples/text_to_image_deep_cache_sdxl_enterprise.py --model /share_nfs/stable-diffusion-xl-base-1.0-int8-deep-cache --width 512 --height 512 --saved_image output_enterprise_deepcache_sdxl.png

```

**Comment by strint** [comment]
cc @clackhan @isidentical
