### ISSUE TITLE
No module named "oneflow"!

### ISSUE THREAD

**Issue by merecesarchviz** [siliconflow/onediff#695]
####  OneFlow version info
Run `python -m oneflow --doctor` and paste it here.

### How To Reproduce
Steps to reproduce the behavior(code or script):

### The complete error message

Traceback (most recent call last):
  File "F:\Ai\ComfyUI\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\Ai\ComfyUI\custom_nodes\onediff_comfy_nodes\__init__.py", line 2, in <module>
    from ._config import _USE_UNET_INT8
  File "F:\Ai\ComfyUI\custom_nodes\onediff_comfy_nodes\_config.py", line 15, in <module>
    import register_comfy  # load plugins
  File "F:\Ai\ComfyUI\custom_nodes\onediff_comfy_nodes\infer_compiler_registry\register_comfy\__init__.py", line 1, in <module>
    from onediff.infer_compiler import register
  File "F:\Ai\ComfyUI\venv\lib\site-packages\onediff\infer_compiler\__init__.py", line 3, in <module>
    import oneflow as flow
ModuleNotFoundError: No module named 'oneflow'

### Additional context
I install it from the comfyui manager

**Comment by strint** [comment]
https://github.com/siliconflow/onediff?tab=readme-ov-file#os-and-gpu-support
