### ISSUE TITLE
AttributeError: 'OneflowGraph' object has no attribute 'inputs_original'

### ISSUE THREAD

**Issue by jackalcooper** [siliconflow/onediff#697]
#### A clear and concise description of what the bug is.

fail to load saved graph of SDXL lightning pipeline

here the load 
```
Traceback (most recent call last):
  File "/data/caishenghang/live_xl/_build/dev/lib/live_xl/priv/runner.py", line 21, in <module>
    import lightning
  File "/data/caishenghang/live_xl/priv/lightning.py", line 120, in <module>
    save_pipe(pipe, args.save_graph_dir)
  File "/home/caishenghang/onediff/onediff_diffusers_extensions/onediffx/compilers/diffusion_pipeline_compiler.py", line 87, in save_pipe
    obj.save_graph(os.path.join(dir, part))
  File "/home/caishenghang/onediff/src/onediff/infer_compiler/with_oneflow_compile.py", line 325, in save_graph
    self.get_graph().save_graph(file_path)
  File "/home/caishenghang/onediff/src/onediff/infer_compiler/utils/cost_util.py", line 48, in clocked
    return func(*args, **kwargs)
  File "/home/caishenghang/onediff/src/onediff/infer_compiler/with_oneflow_compile.py", line 352, in save_graph
    state_dict = self.runtime_state_dict()
  File "/home/caishenghang/.local/lib/python3.8/site-packages/oneflow/nn/graph/graph.py", line 1080, in runtime_state_dict
    return self._dynamic_input_graph_cache.runtime_state_dict(
  File "/home/caishenghang/.local/lib/python3.8/site-packages/oneflow/nn/graph/cache.py", line 132, in runtime_state_dict
    state_dict = graph.runtime_state_dict(with_eager=with_eager)
  File "/home/caishenghang/.local/lib/python3.8/site-packages/oneflow/nn/graph/graph.py", line 1127, in runtime_state_dict
    gen_index_in_tuple, *self.inputs_original[0], **self.inputs_original[1],
  File "/home/caishenghang/.local/lib/python3.8/site-packages/oneflow/nn/graph/graph.py", line 2151, in __getattr__
    raise AttributeError(
AttributeError: 'OneflowGraph' object has no attribute 'inputs_original'
```

**Comment by strint** [comment]
这个是不是 load 来的 graph， 又在做 save ？

**Comment by strint** [comment]
> > 这个是不是 load 来的 graph， 又在做 save ？
> 
> 是的没错

嗯，这个是可以支持。

不过你是什么情况下做的这个操作，是不是没有必要。

**Comment by jackalcooper** [comment]
> 不过你是什么情况下做的这个操作，是不是没有必要。

情况是，我的启动命令，只有一个，没有对只load或者只save做两种区分，我想很多用户都是类似的写法

**Comment by doombeaker** [comment]
这个 oneflow 升级了吗？我今天早上用 comfyui，先升级了 onediff，但是没升级 oneflow，也会遇到了这个问题（AttributeError: 'OneflowGraph' object has no attribute 'inputs_original'）。

但是升级了 oneflow 后，就没有这个问题了。

**Comment by doombeaker** [comment]
不过我是推理时出错。这个是 save 时的问题。我来跟进解决吧

**Comment by doombeaker** [comment]
solved by https://github.com/siliconflow/onediff/pull/702
