### ISSUE TITLE
使用oneflow_compile编译diffusion模型静态图失败

### ISSUE THREAD

**Issue by zhangvia** [siliconflow/onediff#750]
#### OneDiff git commit id
onediff-0.13.0.dev202403200123

####  OneFlow version info
version: 0.9.1.dev20240319+cu118
git_commit: a130148
cmake_build_type: Release
rdma: True
mlir: True

### How To Reproduce
我在这个模型上尝试了编译[repo](https://github.com/ankanbhunia/PIDM).该模型也是基于diffusion方法 unet迭代生成图像的。转换时成功的，但在编译静态图时出现了无效输入参数的问题：
```2024-03-21 05:53:54,129 [INFO] with_oneflow_compile.py:336 - Building a graph for <class 'models.unet_autoenc.BeatGANsAutoencModel'> ...
[ERROR](GRAPH:OneflowGraph_0:OneflowGraph) building graph got error.
2024-03-21 05:53:54,210 [ERROR] with_oneflow_compile.py:187 - Exception in __call__: e=TypeError('\x1b[1m\x1b[38;2;255;000;000mError\x1b[0m: less(): received an invalid combination of arguments. The valid signatures are:\n\t*0: Tensor (Tensor input, Tensor other)\n\t*1: Tensor (Tensor input, Scalar other)\n\t*2: Tensor (Scalar input, Tensor other)\n')
2024-03-21 05:53:54,210 [WARNING] with_oneflow_compile.py:188 - Recompile oneflow module ...
2024-03-21 05:53:54,210 [DEBUG] with_oneflow_compile.py:34 - Convert <class 'models.unet_autoenc.BeatGANsAutoencModel'> ...
2024-03-21 05:53:56,086 [DEBUG] with_oneflow_compile.py:36 - Convert <class 'models.unet_autoenc.BeatGANsAutoencModel'> done!
2024-03-21 05:53:56,122 [INFO] with_oneflow_compile.py:336 - Building a graph for <class 'models.unet_autoenc.BeatGANsAutoencModel'> ...
[ERROR](GRAPH:OneflowGraph_1:OneflowGraph) building graph got error.
2024-03-21 05:53:56,159 [INFO] core.py:570 - virtual tryon:  :-: 6.81
Traceback (most recent call last):
File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/onediff/infer_compiler/with_oneflow_compile.py", line 185, in wrapper
return func(self, *args, **kwargs)
File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/onediff/infer_compiler/utils/graph_management_utils.py", line 82, in wrapper
ret = func(self, *args, **kwargs)
File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/onediff/infer_compiler/with_oneflow_compile.py", line 272, in __call__
output = dpl_graph(*args, **kwargs)
File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 281, in __call__
return self._dynamic_input_graph_cache(*args, **kwargs)
File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/oneflow/nn/graph/cache.py", line 115, in __call__
return graph(*args, **kwargs)
File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 284, in __call__
self._compile(*args, **kwargs)
File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 852, in _compile
return self._compile_new(*args, **kwargs)
File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 871, in _compile_new
_, eager_outputs = self.build_graph(*args, **kwargs)
File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 1374, in build_graph
outputs = self.__build_graph(*args, **kwargs)
File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 1491, in __build_graph
outputs = self.build(*lazy_args, **lazy_kwargs)
File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/onediff/infer_compiler/with_oneflow_compile.py", line 341, in build
return self.model(*args, **kwargs)
File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 186, in __call__
result = self.__block_forward(*args, **kwargs)
File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 236, in __block_forward
result = unbound_forward_of_module_instance(self, *args, **kwargs)
File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/tryon/VirtualTryon/models/unet_autoenc.py", line 158, in forward
cond_mask = prob_mask_like((x.shape[0],), prob = prob, device = x.device)
File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/tryon/VirtualTryon/models/unet_autoenc.py", line 17, in prob_mask_like
return torch.zeros(shape, device = device).float().uniform_(0, 1) < prob
TypeError: Error: less(): received an invalid combination of arguments. The valid signatures are:
*0: Tensor (Tensor input, Tensor other)
*1: Tensor (Tensor input, Scalar other)
*2: Tensor (Scalar input, Tensor other)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/cog/server/worker.py", line 221, in _predict
result = predict(**payload)
File "/media/74nvme/research/tryon/predict.py", line 337, in predict
sr_try, mask_nd_by, hair_nd, input_try, output_try, person_ary, portrait_mask = self.process(data, cloth_path, mote_params, gender,
File "/media/74nvme/research/tryon/predict.py", line 190, in process
rst = self.ArcVTO.generate(mode=t_model, random_seed=-1)
File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/tryon/VirtualTryon.py", line 178, in generate
rst = model.predict(garmentIn, personIn, poseIn, sample_algorithm=sample_algorithm, cond_scale=cond_scale, noise=noise, nsteps=num_steps)
File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/tryon/VirtualTryon/predict.py", line 56, in predict
xs, x0_preds = ddim_steps(noise, seq, self.model, self.betas.cuda(), [src, tgt_pose], cond_scale = cond_scale)
File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/tryon/VirtualTryon/diffusion.py", line 36, in ddim_steps
et = model.forward_with_cond_scale(x = torch.cat([xt, target_pose],1), t = t, cond = cond, cond_scale = cond_scale)[0]
File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/tryon/VirtualTryon/models/unet_autoenc.py", line 123, in forward_with_cond_scale
logits = self.__call__(x, t, cond=cond, prob = 1)
File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/onediff/infer_compiler/utils/args_tree_util.py", line 50, in wrapper
output = func(self, *mapped_args, **mapped_kwargs)
File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/onediff/infer_compiler/with_oneflow_compile.py", line 191, in wrapper
return func(self, *args, **kwargs)
File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/onediff/infer_compiler/utils/graph_management_utils.py", line 82, in wrapper
ret = func(self, *args, **kwargs)
File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/onediff/infer_compiler/with_oneflow_compile.py", line 272, in __call__
output = dpl_graph(*args, **kwargs)
File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 281, in __call__
return self._dynamic_input_graph_cache(*args, **kwargs)
File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/oneflow/nn/graph/cache.py", line 115, in __call__
return graph(*args, **kwargs)
File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 284, in __call__
self._compile(*args, **kwargs)
File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 852, in _compile
return self._compile_new(*args, **kwargs)
File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 871, in _compile_new
_, eager_outputs = self.build_graph(*args, **kwargs)
File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 1374, in build_graph
outputs = self.__build_graph(*args, **kwargs)
File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 1491, in __build_graph
outputs = self.build(*lazy_args, **lazy_kwargs)
File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/onediff/infer_compiler/with_oneflow_compile.py", line 341, in build
return self.model(*args, **kwargs)
File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 186, in __call__
result = self.__block_forward(*args, **kwargs)
File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 236, in __block_forward
result = unbound_forward_of_module_instance(self, *args, **kwargs)
File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/tryon/VirtualTryon/models/unet_autoenc.py", line 158, in forward
cond_mask = prob_mask_like((x.shape[0],), prob = prob, device = x.device)
File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/tryon/VirtualTryon/models/unet_autoenc.py", line 17, in prob_mask_like
return torch.zeros(shape, device = device).float().uniform_(0, 1) < prob
TypeError: Error: less(): received an invalid combination of arguments. The valid signatures are:
*0: Tensor (Tensor input, Tensor other)
*1: Tensor (Tensor input, Scalar other)
*2: Tensor (Scalar input, Tensor other)```

**Comment by strint** [comment]
它的 unet 类型是什么样的？

这里看起来触发了一个算子错误：
```
return torch.zeros(shape, device = device).float().uniform_(0, 1) < prob
TypeError: Error: less(): received an invalid combination of arguments. The valid signatures are:
*0: Tensor (Tensor input, Tensor other)
*1: Tensor (Tensor input, Scalar other)
*2: Tensor (Scalar input, Tensor other)```

```

**Comment by strint** [comment]
```
>>> import oneflow as flow
>>> t = flow.zeros((2),).float().uniform_(0, 1)
>>> t
tensor([0.6024, 0.3124], dtype=oneflow.float32)
>>> t < 0.4
tensor([False,  True], dtype=oneflow.bool)
```

这样是可以工作的。好奇  `torch.zeros(shape, device = device).float().uniform_(0, 1) < prob` 的 less 运算前后分别是什么类型。

**Comment by hjchen2** [comment]
> ```
> >>> import oneflow as flow
> >>> t = flow.zeros((2),).float().uniform_(0, 1)
> >>> t
> tensor([0.6024, 0.3124], dtype=oneflow.float32)
> >>> t < 0.4
> tensor([False,  True], dtype=oneflow.bool)
> ```
> 
> 这样是可以工作的。好奇 `torch.zeros(shape, device = device).float().uniform_(0, 1) < prob` 的 less 运算前后分别是什么类型。

可以在这一行前面打印一下prob的类型

**Comment by zhangvia** [comment]
[https://github.com/ankanbhunia/PIDM/blob/main/models/unet_autoenc.py](https://github.com/ankanbhunia/PIDM/blob/main/models/unet_autoenc.py)这里有网络的结构定义，就是一个简单的unet和一个encoder。这里的报错在forward的第一句就出现了，第一句是这样的：
```
cond_mask = prob_mask_like((x.shape[0],), prob = prob, device = x.device)
```
prob_mask_like的定义如下：
```
def prob_mask_like(shape, prob, device):
    if prob == 1:
        return torch.ones(shape, device = device, dtype = torch.bool)
    elif prob == 0:
        return torch.zeros(shape, device = device, dtype = torch.bool)
    else:
        return torch.zeros(shape, device = device).float().uniform_(0, 1) < prob
```
在else分支出错了，但是prob是0或者1，应该不会走else分支才对。编译图的过程是走了所有的分支吗

**Comment by zhangvia** [comment]
@strint @hjchen2

**Comment by hjchen2** [comment]
你应该安装的是oneflow开源版本，请先卸载oneflow，严格按照onediff提供的方式安装oneflow（https://github.com/siliconflow/onediff?tab=readme-ov-file#installation）

**Comment by zhangvia** [comment]
我就是按照这个安装方式装的。刚刚debug了一下，prob是1或者0，但是进入forward之后变成了none。我尝试把prob转成tensor，但是在这个分支条件判断时报错了，
```
def prob_mask_like(shape, prob, device):
    if prob == 1:
        return torch.ones(shape, device = device, dtype = torch.bool)
    elif prob == 0:
        return torch.zeros(shape, device = device, dtype = torch.bool)
    else:
        return torch.zeros(shape, device = device).float().uniform_(0, 1) < prob
```
错误如下：
```
File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/arcsoft_model_tryon/VirtualTryon/models/unet_autoenc.py", line 12, in prob_mask_like
    if prob :
  File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/oneflow/framework/tensor.py", line 109, in is_nonzero
    value = input.numpy().item()
  File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/oneflow/framework/tensor.py", line 384, in _numpy
    assert (
AssertionError: tensor.numpy() is not allowed to be called in nn.Graph.build(*args) or be called by lazy tensor.

```

**Comment by strint** [comment]
> prob是1或者0，但是进入forward之后变成了none

这个印象中是一个古老的 bug

你用的 oneflow 是这个么：
```
version: 0.9.1.dev20240319+cu118
git_commit: a130148
cmake_build_type: Release
rdma: True
mlir: True
```

感觉没查到这个 commit，另外也缺一个标识，不太像是最新的。

你要不按照这个  https://github.com/siliconflow/onediff?tab=readme-ov-file#installation

安装下，然后打印下 `python -m oneflow --doctor`

**Comment by zhangvia** [comment]
安装了如下版本后，问题解决了：
```
path: ['/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/oneflow']
version: 0.9.1.dev20240401+cu118
git_commit: 4ed3138
cmake_build_type: Release
rdma: True
mlir: True
enterprise: False
```
但仍然在池化层报错了
```
File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 188, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 238, in __block_forward
    result = unbound_forward_of_module_instance(self, *args, **kwargs)
  File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/arcsoft_model_tryon/ArcVirtualTryon/models/blocks.py", line 445, in forward
    return self.op(x)
  File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 188, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 238, in __block_forward
    result = unbound_forward_of_module_instance(self, *args, **kwargs)
  File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/oneflow/nn/modules/pooling.py", line 537, in forward
    return flow._C.avg_pool2d(
TypeError: Error: avg_pool2d(): argument 'divisor_override' must be int32, not <class 'NoneType'>
```
后续修改了builtin_transformer.py的ProxySubmodule，增加了如下判断：
```
        elif (
            isinstance(
                self._oflow_proxy_submod,
                (torch.nn.AvgPool1d,torch.nn.AvgPool2d,torch.nn.AvgPool3d)
            )
            and attribute == "divisor_override"
        ):
            return 0
```
成功编译静态图了，但我看oneflow的avgpool函数中divisor_override参数是默认为0的，理论上不会出现NoneType的情况吧。这里的判断是否对所有的池化都适用？如果是应该可以更新一下oneflow或者onediff吧

**Comment by doombeaker** [comment]
> 后续修改了builtin_transformer.py的ProxySubmodule，增加了如下判断：

感谢反馈，本质是因为底层算子接口没有对齐造成的，目前对齐的 PR 已经合并。使用 2024/4/16 （含）之后的 oneflow 包的话，不需要这个认为 patch 也可以顺利运行了。
