### ISSUE TITLE
关于图片生成尺寸的问题

### ISSUE THREAD

**Issue by Cherwayway** [siliconflow/onediff#764]
似乎不支持512*910的图片生成，试下来height和width只支持32的倍数，想确认一下是不是这样

**Comment by Cherwayway** [comment]
测试下来比如812的长度或者宽度就不行，报错信息：

2024-04-06 12:54:33,858 - ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/lepton/venv/lib/python3.10/site-packages/onediff/infer_compiler/with_oneflow_compile.py", line 185, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/lepton/venv/lib/python3.10/site-packages/onediff/infer_compiler/utils/graph_management_utils.py", line 82, in wrapper
    ret = func(self, *args, **kwargs)
  File "/opt/lepton/venv/lib/python3.10/site-packages/onediff/infer_compiler/with_oneflow_compile.py", line 272, in __call__
    output = dpl_graph(*args, **kwargs)
  File "/opt/lepton/venv/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 297, in __call__
    return self.__run(*args, **kwargs)
  File "/opt/lepton/venv/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 1865, in __run
    _eager_outputs = oneflow._oneflow_internal.nn.graph.RunLazyNNGraphByVM(
oneflow._oneflow_internal.exception.Exception: Check failed: (25 == 26) 
  File "oneflow/core/job/job_interpreter.cpp", line 325, in InterpretJob
    RunNormalOp(launch_context, launch_op, inputs)
  File "oneflow/core/job/job_interpreter.cpp", line 237, in RunNormalOp
    it.Apply(*op, inputs, &outputs, OpExprInterpContext(empty_attr_map, JUST(launch_op.device)))
  File "oneflow/core/framework/op_interpreter/eager_local_op_interpreter.cpp", line 84, in NaiveInterpret
    [&]() -> Maybe<const LocalTensorInferResult> { LocalTensorMetaInferArgs ... mut_local_tensor_infer_cache()->GetOrInfer(infer_args)); }()
  File "oneflow/core/framework/op_interpreter/eager_local_op_interpreter.cpp", line 87, in operator()
    user_op_expr.mut_local_tensor_infer_cache()->GetOrInfer(infer_args)
  File "oneflow/core/framework/local_tensor_infer_cache.cpp", line 210, in GetOrInfer
    Infer(*user_op_expr, infer_args)
  File "oneflow/core/framework/local_tensor_infer_cache.cpp", line 178, in Infer
    user_op_expr.InferPhysicalTensorDesc( infer_args.attrs ... ) -> TensorMeta* { return &output_mut_metas.at(i); })
  File "oneflow/core/framework/op_expr.cpp", line 602, in InferPhysicalTensorDesc
    physical_tensor_desc_infer_fn_(&infer_ctx)
  File "oneflow/user/ops/concat_op.cpp", line 55, in InferLogicalTensorDesc
    CHECK_EQ_OR_RETURN(in_desc.shape().At(i), out_dim_vec.at(i))
Error Type: oneflow.ErrorProto.check_failed_error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/lepton/venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/opt/lepton/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/opt/lepton/venv/lib/python3.10/site-packages/fastapi/applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/lepton/venv/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/lepton/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/opt/lepton/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/opt/lepton/venv/lib/python3.10/site-packages/prometheus_fastapi_instrumentator/middleware.py", line 174, in __call__
    raise exc
  File "/opt/lepton/venv/lib/python3.10/site-packages/prometheus_fastapi_instrumentator/middleware.py", line 172, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/opt/lepton/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/opt/lepton/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/opt/lepton/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/opt/lepton/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/opt/lepton/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/opt/lepton/venv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/opt/lepton/venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/opt/lepton/venv/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/opt/lepton/venv/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/opt/lepton/venv/lib/python3.10/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/opt/lepton/venv/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/opt/lepton/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/lepton/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/opt/lepton/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/root/.cache/lepton/github.com/AUTOMATIC1111/stable-diffusion-webui.git/modules/api/api.py", line 377, in text2imgapi
    processed = scripts.scripts_txt2img.run(p, *p.script_args) # Need to pass args as list here
  File "/root/.cache/lepton/github.com/AUTOMATIC1111/stable-diffusion-webui.git/modules/scripts.py", line 601, in run
    processed = script.run(p, *script_args)
  File "/root/.cache/lepton/github.com/AUTOMATIC1111/stable-diffusion-webui.git/extensions/onediff_sd_webui_extensions/scripts/onediff.py", line 205, in run
    proc = process_images(p)
  File "/root/.cache/lepton/github.com/AUTOMATIC1111/stable-diffusion-webui.git/modules/processing.py", line 732, in process_images
    res = process_images_inner(p)
  File "/root/.cache/lepton/github.com/AUTOMATIC1111/stable-diffusion-webui.git/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 42, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "/root/.cache/lepton/github.com/AUTOMATIC1111/stable-diffusion-webui.git/modules/processing.py", line 867, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "/root/.cache/lepton/github.com/AUTOMATIC1111/stable-diffusion-webui.git/modules/processing.py", line 1140, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "/root/.cache/lepton/github.com/AUTOMATIC1111/stable-diffusion-webui.git/modules/sd_samplers_kdiffusion.py", line 235, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "/root/.cache/lepton/github.com/AUTOMATIC1111/stable-diffusion-webui.git/modules/sd_samplers_common.py", line 261, in launch_sampling
    return func()
  File "/root/.cache/lepton/github.com/AUTOMATIC1111/stable-diffusion-webui.git/modules/sd_samplers_kdiffusion.py", line 235, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "/opt/lepton/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/.cache/lepton/github.com/AUTOMATIC1111/stable-diffusion-webui.git/repositories/k-diffusion/k_diffusion/sampling.py", line 594, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "/opt/lepton/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/lepton/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/lepton/github.com/AUTOMATIC1111/stable-diffusion-webui.git/modules/sd_samplers_cfg_denoiser.py", line 169, in forward
    x_out = self.inner_model(x_in, sigma_in, cond=make_condition_dict(cond_in, image_cond_in))
  File "/opt/lepton/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/lepton/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/lepton/github.com/AUTOMATIC1111/stable-diffusion-webui.git/repositories/k-diffusion/k_diffusion/external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "/root/.cache/lepton/github.com/AUTOMATIC1111/stable-diffusion-webui.git/repositories/k-diffusion/k_diffusion/external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "/root/.cache/lepton/github.com/AUTOMATIC1111/stable-diffusion-webui.git/modules/sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "/root/.cache/lepton/github.com/AUTOMATIC1111/stable-diffusion-webui.git/modules/sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "/root/.cache/lepton/github.com/AUTOMATIC1111/stable-diffusion-webui.git/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "/opt/lepton/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/lepton/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/lepton/github.com/AUTOMATIC1111/stable-diffusion-webui.git/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 1335, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "/opt/lepton/venv/lib/python3.10/site-packages/onediff/infer_compiler/utils/args_tree_util.py", line 50, in wrapper
    output = func(self, *mapped_args, **mapped_kwargs)
  File "/opt/lepton/venv/lib/python3.10/site-packages/onediff/infer_compiler/with_oneflow_compile.py", line 191, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/lepton/venv/lib/python3.10/site-packages/onediff/infer_compiler/utils/graph_management_utils.py", line 82, in wrapper
    ret = func(self, *args, **kwargs)
  File "/opt/lepton/venv/lib/python3.10/site-packages/onediff/infer_compiler/with_oneflow_compile.py", line 272, in __call__
    output = dpl_graph(*args, **kwargs)
  File "/opt/lepton/venv/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 295, in __call__
    self._compile(*args, **kwargs)
  File "/opt/lepton/venv/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 861, in _compile
    return self._dynamic_input_graph_cache._compile(*args, **kwargs)
  File "/opt/lepton/venv/lib/python3.10/site-packages/oneflow/nn/graph/cache.py", line 121, in _compile
    return graph._compile(*args, **kwargs)
  File "/opt/lepton/venv/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 865, in _compile
    return self._compile_new(*args, **kwargs)
  File "/opt/lepton/venv/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 884, in _compile_new
    _, eager_outputs = self.build_graph(*args, **kwargs)
  File "/opt/lepton/venv/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 1432, in build_graph
    outputs = self.__build_graph(*args, **kwargs)
  File "/opt/lepton/venv/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 1580, in __build_graph
    outputs = self.build(*lazy_args, **lazy_kwargs)
  File "/opt/lepton/venv/lib/python3.10/site-packages/onediff/infer_compiler/with_oneflow_compile.py", line 341, in build
    return self.model(*args, **kwargs)
  File "/opt/lepton/venv/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 188, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/opt/lepton/venv/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 238, in __block_forward
    result = unbound_forward_of_module_instance(self, *args, **kwargs)
  File "/root/.cache/lepton/github.com/AUTOMATIC1111/stable-diffusion-webui.git/extensions/onediff_sd_webui_extensions/compile_ldm.py", line 43, in forward
    h = flow.cat([h, hs.pop()], dim=1)
RuntimeError: Error: Sizes of tensors must match except in dimension 1. Got 25 and 26 is expected in dimension 2.

**Comment by doombeaker** [comment]
resovled by https://github.com/siliconflow/onediff/pull/847
