### ISSUE TITLE
comfyui上安装onediff的插件，在启动时候出现错误

### ISSUE THREAD

**Issue by ywdong** [siliconflow/onediff#771]
#### A clear and concise description of what the bug is.
安装没有错误，但是在comfyui启动时候会出现错误如下：
Traceback (most recent call last):
  File "/mnt/bn/ken-code-volumn/code/hugh/github/ComfyUI/nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/bn/ken-code-volumn/code/hugh/github/ComfyUI/custom_nodes/onediff_comfy_nodes/__init__.py", line 2, in <module>
    from ._config import _USE_UNET_INT8
  File "/mnt/bn/ken-code-volumn/code/hugh/github/ComfyUI/custom_nodes/onediff_comfy_nodes/_config.py", line 15, in <module>
    import register_comfy  # load plugins
    ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/bn/ken-code-volumn/code/hugh/github/ComfyUI/custom_nodes/onediff_comfy_nodes/infer_compiler_registry/register_comfy/__init__.py", line 1, in <module>
    from onediff.infer_compiler import register
ModuleNotFoundError: No module named 'onediff.infer_compiler'

Cannot import /mnt/bn/ken-code-volumn/code/hugh/github/ComfyUI/custom_nodes/onediff_comfy_nodes module for custom nodes: No module named 'onediff.infer_compiler'

### Your environment
Python version: 311
OS: Linux
OS bit: 64
Platform tag: cp311-cp311-manylinux_2_31_x86_64

####  OneFlow version info
path: ['/mnt/bn/ken-code-volumn/code/hugh/miniconda3/lib/python3.11/site-packages/oneflow']
version: 0.9.1.dev20240324+cu118
git_commit: 0523481
cmake_build_type: Release
rdma: True
mlir: True
enterprise: False

### How To Reproduce
Steps to reproduce the behavior(code or script):

**Comment by ccssu** [comment]
> ModuleNotFoundError: No module named 'onediff.infer_compiler'
@ywdong 
### Error Analysis:

The error you're encountering is likely due to conflicting imports from different directories named "onediff". This conflict arises because there is a directory named "onediff" in the current working directory, along with the "onediff" repository. This confuses the Python interpreter during package import.

### Solutions:

1. **Delete Redundant Directory:**
   - Delete the unnecessary "onediff" directory to remove the conflict.

2. **Manually Adjust Import Priority:**
   - Modify the import priority manually to ensure that the correct "onediff" package is imported. You can achieve this by adding the path to the desired "onediff" directory at the beginning of the Python path using `sys.path.insert(0, "path/to/onediff/src")` in the `main.py` file.

**Comment by ywdong** [comment]
> > ModuleNotFoundError: No module named 'onediff.infer_compiler'ModuleNotFoundError：没有名为“onediff.infer_compiler”的模块
> > @ywdong
> 
> ### Error Analysis: 错误分析：
> The error you're encountering is likely due to conflicting imports from different directories named "onediff". This conflict arises because there is a directory named "onediff" in the current working directory, along with the "onediff" repository. 您遇到的错误可能是由于来自名为“onediff”的不同目录的导入发生冲突。出现此冲突的原因是当前工作目录中有一个名为“onediff”的目录以及“onediff”存储库。This confuses the Python interpreter during package import.这会在包导入期间使 Python 解释器感到困惑。
> 
> ### Solutions: 解决方案：
> 1. **Delete Redundant Directory:删除冗余目录：**
>    
>    * Delete the unnecessary "onediff" directory to remove the conflict.删除不必要的“onediff”目录以消除冲突。
> 2. **Manually Adjust Import Priority:手动调整导入优先级：**
>    
>    * Modify the import priority manually to ensure that the correct "onediff" package is imported. You can achieve this by adding the path to the desired "onediff" directory at the beginning of the Python path using `sys.path.insert(0, "path/to/onediff/src")` in the `main.py` file.手动修改导入优先级以确保导入正确的“onediff”包。您可以通过在 `main.py` 文件中使用 `sys.path.insert(0, "path/to/onediff/src")` 在 Python 路径的开头添加所需的“onediff”目录的路径来实现此目的。

------------------------------------------------------------------------------------------------------------
Thx guys. I remove the onediff dir, but I got the below error :

Traceback (most recent call last):
  File "/mnt/bn/ken-code-volumn/code/hugh/github/ComfyUI/nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/bn/ken-code-volumn/code/hugh/github/ComfyUI/custom_nodes/onediff_comfy_nodes/__init__.py", line 2, in <module>
    from ._config import _USE_UNET_INT8
  File "/mnt/bn/ken-code-volumn/code/hugh/github/ComfyUI/custom_nodes/onediff_comfy_nodes/_config.py", line 15, in <module>
    import register_comfy  # load plugins
    ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/bn/ken-code-volumn/code/hugh/github/ComfyUI/custom_nodes/onediff_comfy_nodes/infer_compiler_registry/register_comfy/__init__.py", line 1, in <module>
    from onediff.infer_compiler import register
ModuleNotFoundError: No module named 'onediff'

Cannot import /mnt/bn/ken-code-volumn/code/hugh/github/ComfyUI/custom_nodes/onediff_comfy_nodes module for custom nodes: No module named 'onediff'

**Comment by ywdong** [comment]
我重新安装了onediff，问题解决了。Many thx~
