### ISSUE TITLE
DeepCache: ComfyUI always fails with Error  object has no attribute 'model_lowvram'

### ISSUE THREAD

**Issue by jwstegemann** [siliconflow/onediff#772]
### Describe the bug
Running the example workflow for DeepCache in ComfyUI I always get the following error: 
`AttributeError: 'OneFlowDeepCacheSpeedUpModelPatcher' object has no attribute 'model_lowvram'`

### Your environment
Amazon Linux 2, Cuda 121, Pytorch 2.2

#### OneDiff git commit id
089489a11a3da876ad1ca2abc18b798af940a0bb

####  OneFlow version info
libibverbs not available, ibv_fork_init skipped
path: ['/venv/comfyui/lib/python3.11/site-packages/oneflow']
version: 0.9.1.dev20240328+cu121
git_commit: 06b10cc
cmake_build_type: Release
rdma: True
mlir: True
enterprise: False

### How To Reproduce
Open Workflow in ComfyUI and run it. Error appears on VAE-node.

### The complete error message
````
!!! Exception during processing !!!
Traceback (most recent call last):
  File "/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ComfyUI/nodes.py", line 288, in decode
    return (vae.decode(samples["samples"]), )
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ComfyUI/comfy/sd.py", line 285, in decode
    model_management.load_models_gpu([self.patcher], memory_required=memory_used)
  File "/ComfyUI/comfy/model_management.py", line 416, in load_models_gpu
    free_memory(total_memory_required[device] * 1.3 + extra_mem, device, models_already_loaded)
  File "/ComfyUI/comfy/model_management.py", line 366, in free_memory
    current_loaded_models[i].model_unload()
  File "/ComfyUI/comfy/model_management.py", line 312, in model_unload
    self.model.unpatch_model(self.model.offload_device, unpatch_weights=unpatch_weights)
  File "/ComfyUI/comfy/model_patcher.py", line 436, in unpatch_model
    if self.model_lowvram:
       ^^^^^^^^^^^^^^^^^^
AttributeError: 'OneFlowDeepCacheSpeedUpModelPatcher' object has no attribute 'model_lowvram'
```

### Additional context

**Comment by strint** [comment]
Fixed in: https://github.com/siliconflow/onediff/pull/774
