### ISSUE TITLE
AttributeError: module 'oneflow.sysconfig' has no attribute 'with_enterprise'

### ISSUE THREAD

**Issue by johnsmith0031** [siliconflow/onediff#781]
#### A clear and concise description of what the bug is.

When starting ComfyUI, it throw the error and cannot load the node.
AttributeError: module 'oneflow.sysconfig' has no attribute 'with_enterprise'
Does onediff support oneflow community version?

#### OS 

Python version: 3.10.6
OS: Windows 10 + WSL 2
OS bit: 64

#### OneDiff git commit id
62287c035ee28d0b46a962a5bf00da42c11a8326

installed with:
```
git clone https://github.com/siliconflow/onediff.git
cd onediff && python3 -m pip install -e .
```

#### ComfyUI commit id
b3e97fc7141681b1fa6da3ee6701c0f9a31d38f8

####  OneFlow version info
path: ['/home/johnsmith/sd_venv_onediff/lib/python3.10/site-packages/oneflow']
version: 0.9.1.dev20240402+cu121
git_commit: a130148
cmake_build_type: Release
rdma: True
mlir: True

### How To Reproduce
Steps to reproduce the behavior(code or script):
```bash
#!/bin/bash
source ~/sd_venv_onediff/bin/activate

# Try using TCMalloc on Linux
prepare_tcmalloc() {
    if [[ "${OSTYPE}" == "linux"* ]] && [[ -z "${NO_TCMALLOC}" ]] && [[ -z "${LD_PRELOAD}" ]]; then
        TCMALLOC="$(PATH=/usr/sbin:$PATH ldconfig -p | grep -Po "libtcmalloc(_minimal|)\.so\.\d" | head -n 1)"
        if [[ ! -z "${TCMALLOC}" ]]; then
            echo "Using TCMalloc: ${TCMALLOC}"
            export LD_PRELOAD="${TCMALLOC}"
        else
            printf "\e[1m\e[31mCannot locate TCMalloc (improves CPU memory usage)\e[0m\n"
        fi
    fi
}

prepare_tcmalloc
NVIDIA_PATH=/home/johnsmith/sd_venv_onediff/lib/python3.10/site-packages/nvidia
export LD_LIBRARY_PATH=$NVIDIA_PATH:$NVIDIA_PATH/cudnn/lib:$NVIDIA_PATH/cublas/lib:/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH

python main.py --listen=0.0.0.0 --port=7860 --output-directory=./output/
```

### The complete error message

```python
Traceback (most recent call last):
  File "/home/johnsmith/ComfyUI/nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/johnsmith/ComfyUI/custom_nodes/onediff_comfy_nodes/__init__.py", line 2, in <module>
    from ._config import _USE_UNET_INT8
  File "/home/johnsmith/ComfyUI/custom_nodes/onediff_comfy_nodes/_config.py", line 18, in <module>
    if is_community_version():
  File "/home/johnsmith/sd_venv_onediff/custom/onediff/src/onediff/infer_compiler/utils/version_util.py", line 31, in is_community_version
    return not oneflow.sysconfig.with_enterprise()
AttributeError: module 'oneflow.sysconfig' has no attribute 'with_enterprise'
```

### Additional context
When fixed it manually, the node can be loaded, but cannot compile the graph.

Quick fix:
```python
def is_community_version():
    return True
```

Extra Error Message:
```python
WARNING [2024-04-03 10:14:12] /home/johnsmith/sd_venv_onediff/custom/onediff/src/onediff/infer_compiler/utils/log_utils.py:33 - Logging handlers already exist for ONEDIFF
ERROR [2024-04-03 10:14:14] /home/johnsmith/sd_venv_onediff/custom/onediff/src/onediff/infer_compiler/with_oneflow_compile.py:188 - Exception in __call__: e=NotImplementedError("Transform failed of <class 'register_comfy.deep_cache_unet.DeepCacheUNet'>: Transform failed of <class 'onediff.infer_compiler.with_oneflow_compile.get_mixed_deployable_module.<locals>.MixedDeployableModule'>: 'function' object has no attribute '<locals>'")
WARNING [2024-04-03 10:14:14] /home/johnsmith/sd_venv_onediff/custom/onediff/src/onediff/infer_compiler/with_oneflow_compile.py:189 - Recompile oneflow module ...
  0%|                                                                                                                                                                                         | 0/20 [00:02<?, ?it/s]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/home/johnsmith/sd_venv_onediff/custom/onediff/src/onediff/infer_compiler/transform/builtin_transform.py", line 37, in wrapper
    result = dispatcher(first_param, *args, **kwargs)
  File "/usr/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/johnsmith/sd_venv_onediff/custom/onediff/src/onediff/infer_compiler/transform/builtin_transform.py", line 188, in _
    new_md_cls = proxy_class(type(mod))
  File "/home/johnsmith/sd_venv_onediff/custom/onediff/src/onediff/infer_compiler/transform/builtin_transform.py", line 57, in proxy_class
    return transform_mgr.transform_cls(cls)
  File "/home/johnsmith/sd_venv_onediff/custom/onediff/src/onediff/infer_compiler/transform/manager.py", line 82, in transform_cls
    mock_cls = self._transform_entity(mock_full_cls_name)
  File "/home/johnsmith/sd_venv_onediff/custom/onediff/src/onediff/infer_compiler/transform/manager.py", line 59, in _transform_entity
    result = self.mocker.mock_entity(entity)
  File "/home/johnsmith/sd_venv_onediff/custom/onediff/src/onediff/infer_compiler/import_tools/importer.py", line 93, in mock_entity
    return self.load_entity_with_mock(entity)
  File "/home/johnsmith/sd_venv_onediff/custom/onediff/src/onediff/infer_compiler/import_tools/importer.py", line 130, in load_entity_with_mock
    mock_pkg = getattr(mock_pkg, name)
AttributeError: 'function' object has no attribute '<locals>'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/johnsmith/sd_venv_onediff/custom/onediff/src/onediff/infer_compiler/transform/builtin_transform.py", line 37, in wrapper
    result = dispatcher(first_param, *args, **kwargs)
  File "/usr/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/johnsmith/sd_venv_onediff/custom/onediff/src/onediff/infer_compiler/transform/builtin_transform.py", line 232, in _
    of_mod = of_mod_cls()
  File "/home/johnsmith/sd_venv_onediff/custom/onediff/src/onediff/infer_compiler/transform/builtin_transform.py", line 203, in init
    self._modules[n] = torch2oflow(m)
  File "/home/johnsmith/sd_venv_onediff/custom/onediff/src/onediff/infer_compiler/transform/builtin_transform.py", line 39, in wrapper
    raise NotImplementedError(f"Transform failed of {type(first_param)}: {e}")
NotImplementedError: Transform failed of <class 'onediff.infer_compiler.with_oneflow_compile.get_mixed_deployable_module.<locals>.MixedDeployableModule'>: 'function' object has no attribute '<locals>'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/johnsmith/sd_venv_onediff/custom/onediff/src/onediff/infer_compiler/with_oneflow_compile.py", line 186, in wrapper
    return func(self, *args, **kwargs)
  File "/home/johnsmith/sd_venv_onediff/custom/onediff/src/onediff/infer_compiler/utils/graph_management_utils.py", line 86, in wrapper
    ret = func(self, *args, **kwargs)
  File "/home/johnsmith/sd_venv_onediff/custom/onediff/src/onediff/infer_compiler/with_oneflow_compile.py", line 272, in __call__
    dpl_graph = self.get_graph()
  File "/home/johnsmith/sd_venv_onediff/custom/onediff/src/onediff/infer_compiler/with_oneflow_compile.py", line 239, in get_graph
    self._deployable_module_model.oneflow_module,
  File "/home/johnsmith/sd_venv_onediff/custom/onediff/src/onediff/infer_compiler/with_oneflow_compile.py", line 35, in oneflow_module
    self._oneflow_module = torch2oflow(self._torch_module)
  File "/home/johnsmith/sd_venv_onediff/custom/onediff/src/onediff/infer_compiler/transform/builtin_transform.py", line 39, in wrapper
    raise NotImplementedError(f"Transform failed of {type(first_param)}: {e}")
NotImplementedError: Transform failed of <class 'register_comfy.deep_cache_unet.DeepCacheUNet'>: Transform failed of <class 'onediff.infer_compiler.with_oneflow_compile.get_mixed_deployable_module.<locals>.MixedDeployableModule'>: 'function' object has no attribute '<locals>'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/johnsmith/sd_venv_onediff/custom/onediff/src/onediff/infer_compiler/transform/builtin_transform.py", line 37, in wrapper
    result = dispatcher(first_param, *args, **kwargs)
  File "/usr/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/johnsmith/sd_venv_onediff/custom/onediff/src/onediff/infer_compiler/transform/builtin_transform.py", line 188, in _
    new_md_cls = proxy_class(type(mod))
  File "/home/johnsmith/sd_venv_onediff/custom/onediff/src/onediff/infer_compiler/transform/builtin_transform.py", line 57, in proxy_class
    return transform_mgr.transform_cls(cls)
  File "/home/johnsmith/sd_venv_onediff/custom/onediff/src/onediff/infer_compiler/transform/manager.py", line 82, in transform_cls
    mock_cls = self._transform_entity(mock_full_cls_name)
  File "/home/johnsmith/sd_venv_onediff/custom/onediff/src/onediff/infer_compiler/transform/manager.py", line 59, in _transform_entity
    result = self.mocker.mock_entity(entity)
  File "/home/johnsmith/sd_venv_onediff/custom/onediff/src/onediff/infer_compiler/import_tools/importer.py", line 93, in mock_entity
    return self.load_entity_with_mock(entity)
  File "/home/johnsmith/sd_venv_onediff/custom/onediff/src/onediff/infer_compiler/import_tools/importer.py", line 130, in load_entity_with_mock
    mock_pkg = getattr(mock_pkg, name)
AttributeError: 'function' object has no attribute '<locals>'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/johnsmith/sd_venv_onediff/custom/onediff/src/onediff/infer_compiler/transform/builtin_transform.py", line 37, in wrapper
    result = dispatcher(first_param, *args, **kwargs)
  File "/usr/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/johnsmith/sd_venv_onediff/custom/onediff/src/onediff/infer_compiler/transform/builtin_transform.py", line 232, in _
    of_mod = of_mod_cls()
  File "/home/johnsmith/sd_venv_onediff/custom/onediff/src/onediff/infer_compiler/transform/builtin_transform.py", line 203, in init
    self._modules[n] = torch2oflow(m)
  File "/home/johnsmith/sd_venv_onediff/custom/onediff/src/onediff/infer_compiler/transform/builtin_transform.py", line 39, in wrapper
    raise NotImplementedError(f"Transform failed of {type(first_param)}: {e}")
NotImplementedError: Transform failed of <class 'onediff.infer_compiler.with_oneflow_compile.get_mixed_deployable_module.<locals>.MixedDeployableModule'>: 'function' object has no attribute '<locals>'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/johnsmith/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/johnsmith/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/johnsmith/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/johnsmith/ComfyUI/nodes.py", line 1368, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "/home/johnsmith/ComfyUI/nodes.py", line 1338, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "/home/johnsmith/ComfyUI/comfy/sample.py", line 100, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/home/johnsmith/ComfyUI/comfy/samplers.py", line 706, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/home/johnsmith/ComfyUI/comfy/samplers.py", line 611, in sample
    samples = sampler.sample(model_wrap, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "/home/johnsmith/ComfyUI/comfy/samplers.py", line 550, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "/home/johnsmith/sd_venv_onediff/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/johnsmith/ComfyUI/comfy/k_diffusion/sampling.py", line 154, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "/home/johnsmith/sd_venv_onediff/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/johnsmith/sd_venv_onediff/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/johnsmith/ComfyUI/comfy/samplers.py", line 282, in forward
    out = self.inner_model(x, sigma, cond=cond, uncond=uncond, cond_scale=cond_scale, model_options=model_options, seed=seed)
  File "/home/johnsmith/sd_venv_onediff/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/johnsmith/sd_venv_onediff/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/johnsmith/ComfyUI/comfy/samplers.py", line 272, in forward
    return self.apply_model(*args, **kwargs)
  File "/home/johnsmith/ComfyUI/comfy/samplers.py", line 269, in apply_model
    out = sampling_function(self.inner_model, x, timestep, uncond, cond, cond_scale, model_options=model_options, seed=seed)
  File "/home/johnsmith/ComfyUI/comfy/samplers.py", line 249, in sampling_function
    cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
  File "/home/johnsmith/ComfyUI/custom_nodes/onediff_comfy_nodes/modules/sd_hijack_utils.py", line 41, in <lambda>
    lambda *args, **kwargs: self(*args, **kwargs),
  File "/home/johnsmith/ComfyUI/custom_nodes/onediff_comfy_nodes/modules/sd_hijack_utils.py", line 57, in __call__
    return self.__sub_func(self.__orig_func, *args, **kwargs)
  File "/home/johnsmith/ComfyUI/custom_nodes/onediff_comfy_nodes/modules/hijack_samplers.py", line 98, in new_calc_cond_uncond_batch
    output = model_options['model_function_wrapper'](model.apply_model, {"input": input_x, "timestep": timestep_, "c": c, "cond_or_uncond": cond_or_uncond}).chunk(batch_chunks)
  File "/home/johnsmith/ComfyUI/custom_nodes/onediff_comfy_nodes/utils/deep_cache_speedup.py", line 101, in apply_model
    model_output, cache_h = model_patcher.deep_cache_unet(
  File "/home/johnsmith/sd_venv_onediff/custom/onediff/src/onediff/infer_compiler/utils/args_tree_util.py", line 50, in wrapper
    output = func(self, *mapped_args, **mapped_kwargs)
  File "/home/johnsmith/sd_venv_onediff/custom/onediff/src/onediff/infer_compiler/with_oneflow_compile.py", line 192, in wrapper
    return func(self, *args, **kwargs)
  File "/home/johnsmith/sd_venv_onediff/custom/onediff/src/onediff/infer_compiler/utils/graph_management_utils.py", line 86, in wrapper
    ret = func(self, *args, **kwargs)
  File "/home/johnsmith/sd_venv_onediff/custom/onediff/src/onediff/infer_compiler/with_oneflow_compile.py", line 272, in __call__
    dpl_graph = self.get_graph()
  File "/home/johnsmith/sd_venv_onediff/custom/onediff/src/onediff/infer_compiler/with_oneflow_compile.py", line 239, in get_graph
    self._deployable_module_model.oneflow_module,
  File "/home/johnsmith/sd_venv_onediff/custom/onediff/src/onediff/infer_compiler/with_oneflow_compile.py", line 35, in oneflow_module
    self._oneflow_module = torch2oflow(self._torch_module)
  File "/home/johnsmith/sd_venv_onediff/custom/onediff/src/onediff/infer_compiler/transform/builtin_transform.py", line 39, in wrapper
    raise NotImplementedError(f"Transform failed of {type(first_param)}: {e}")
NotImplementedError: Transform failed of <class 'register_comfy.deep_cache_unet.DeepCacheUNet'>: Transform failed of <class 'onediff.infer_compiler.with_oneflow_compile.get_mixed_deployable_module.<locals>.MixedDeployableModule'>: 'function' object has no attribute '<locals>'
```

The workflow is:
![image](https://github.com/siliconflow/onediff/assets/16870323/0281f334-1095-41ad-a91d-a647a13e2b1a)

And similar error also occurs in latest version of ComfyUI.
Does onediff need oneflow-enterprise to work properly?

**Comment by strint** [comment]
> OneFlow version info
> path: ['/home/johnsmith/sd_venv_onediff/lib/python3.10/site-packages/oneflow']
> version: 0.9.1.dev20240402+cu121
> git_commit: a130148
> cmake_build_type: Release
> rdma: True
> mlir: True

This is an old oneflow version.

You need to re-install oneflow  from here: https://github.com/siliconflow/onediff/tree/main?tab=readme-ov-file#1-install-oneflow

**Comment by johnsmith0031** [comment]
> This is an old oneflow version.
> 
> You need to re-install oneflow from here: https://github.com/siliconflow/onediff/tree/main?tab=readme-ov-file#1-install-oneflow

It seems that this site only have 0.9.1.dev available. Which version should I use and where can I get a higher version?
![image](https://github.com/siliconflow/onediff/assets/16870323/e8330183-0557-4cbc-b499-d32892712c08)

**Comment by strint** [comment]
> Is the community version on another fork so the original repo does not contain those commit ids?

Yes, onediff is using a special version oneflow which is optimized for  onediff

**Comment by strint** [comment]
> If I use load checkpoint onediff node, when compiling graph, it'll ran out of memory. I'm using RTX 3060 12G VRAM with 128G RAM.

Which model are you running?

If it's SDXL, 1024 * 1024 image usually need at least 14G VRAM.

**Comment by johnsmith0031** [comment]
> > If I use load checkpoint onediff node, when compiling graph, it'll ran out of memory. I'm using RTX 3060 12G VRAM with 128G RAM.
> 
> Which model are you running?
> 
> If it's SDXL, 1024 * 1024 image usually need at least 14G VRAM.

It's SDXL, load checkpoint node + model speedup node works, but load checkpoint onediff node does not. Is this node depreciated and would be deleted in the future?

**Comment by strint** [comment]
> but load checkpoint onediff node does not.

What is the error message?

**Comment by johnsmith0031** [comment]
> > This is an old oneflow version.
> > You need to re-install oneflow from here: https://github.com/siliconflow/onediff/tree/main?tab=readme-ov-file#1-install-oneflow
> 
> Edit: Reinstalled oneflow and it works! Checked on oneflow's repo on github and cannot find the commit ids from other issues. Is the community version on another fork so the original repo does not contain those commit ids? ![image](https://private-user-images.githubusercontent.com/16870323/319055238-bc893cf2-82cf-4342-b696-62b8e57a8d20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNTE3NDgsIm5iZiI6MTcxMjE1MTQ0OCwicGF0aCI6Ii8xNjg3MDMyMy8zMTkwNTUyMzgtYmM4OTNjZjItODJjZi00MzQyLWI2OTYtNjJiOGU1N2E4ZDIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDEzMzcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0YjIzNjc5YTdkZWJhNGRhZjBhZTk4YzdjNDU3YjdiZWU1MDM5YjBiNjIxMjYyYjIyYjkwMjUxNzFiNWY4MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RpOFzebYARQDlHGFMBl-4ZmnRfwFEfiD9bwZoHlScb4)
> 
> Edit2: If I use load checkpoint onediff node, when compiling graph, it'll ran out of memory. I'm using RTX 3060 12G VRAM with 128G RAM.
> 
> ```
> Building a graph for <class 'register_comfy.openaimodel.UNetModel'> ...
> terminate called after throwing an instance of 'oneflow::RuntimeException'
>   what():  Error: out of memory
> Error message from /home/ci-user/gha-runners/workspace/builder/oneflow/oneflow/oneflow/core/vm/op_call_instruction_policy.cpp:324
>         OpCallInstructionUtil::Compute(this, instruction->mut_stream(), true, false): copy:OpCall:s_d2h
> 
>   File "oneflow/core/vm/op_call_instruction_policy.cpp", line 324, in Compute
>     OpCallInstructionUtil::Compute(this, instruction->mut_stream(), true, false)
>   File "oneflow/core/vm/op_call_instruction_policy.cpp", line 93, in Compute
>     ComputeImpl()
>   File "oneflow/core/vm/op_call_instruction_policy.cpp", line 54, in operator()
>     AllocateOutputBlobsMemory(op_call_instruction_policy, allocator, vm_stream)
>   File "oneflow/core/vm/op_call_instruction_policy.cpp", line 136, in AllocateOutputBlobsMemory
>     allocator->Allocate(&dptr, total_size)
>   File "oneflow/core/vm/bin_allocator.h", line 392, in Allocate
>     AllocateBlockToExtendTotalMem(aligned_size)
>   File "oneflow/core/vm/bin_allocator.h", line 305, in AllocateBlockToExtendTotalMem
>     backend_->Allocate(&mem_ptr, final_allocate_bytes)
>   File "oneflow/core/vm/ep_backend_host_allocator.cpp", line 25, in Allocate
>     ep_device_->AllocPinned(allocation_options_, reinterpret_cast<void**>(mem_ptr), size)
> Error Type: oneflow.ErrorProto.runtime_error
>   File "oneflow/core/vm/op_call_instruction_policy.cpp", line 324, in operator()
> Error Type: oneflow.ErrorProto.runtime_error
> Related Python stack trace:
>   <unknown>
> 
> Stack trace (most recent call last) in thread 8390:
>    Object "/home/johnsmith/sd_venv_onediff/lib/python3.10/site-packages/oneflow/../oneflow.libs/liboneflow-6c8f8a22.so", at 0x7fb1a1066107, in 
>    Object "/home/johnsmith/sd_venv_onediff/lib/python3.10/site-packages/oneflow/../oneflow.libs/liboneflow-6c8f8a22.so", at 0x7fb1a1065967, in 
>    Object "/home/johnsmith/sd_venv_onediff/lib/python3.10/site-packages/oneflow/../oneflow.libs/liboneflow-6c8f8a22.so", at 0x7fb1a10611f8, in vm::ThreadCtx::TryReceiveAndRun()
>    Object "/home/johnsmith/sd_venv_onediff/lib/python3.10/site-packages/oneflow/../oneflow.libs/liboneflow-6c8f8a22.so", at 0x7fb1a1003994, in vm::EpStreamPolicyBase::Run(vm::Instruction*) const
>    Object "/home/johnsmith/sd_venv_onediff/lib/python3.10/site-packages/oneflow/../oneflow.libs/liboneflow-6c8f8a22.so", at 0x7fb1a1006c97, in vm::Instruction::Compute()
>    Object "/home/johnsmith/sd_venv_onediff/lib/python3.10/site-packages/oneflow/../oneflow.libs/liboneflow-6c8f8a22.so", at 0x7fb1a100e078, in vm::OpCallInstructionPolicy::Compute(vm::Instruction*)
>    Object "/home/johnsmith/sd_venv_onediff/lib/python3.10/site-packages/oneflow/../oneflow.libs/liboneflow-6c8f8a22.so", at 0x7fb1a100dd49, in 
>    Object "/home/johnsmith/sd_venv_onediff/lib/python3.10/site-packages/oneflow/../oneflow.libs/liboneflow-6c8f8a22.so", at 0x7fb1a1008e9a, in 
>    Object "/home/johnsmith/sd_venv_onediff/lib/python3.10/site-packages/oneflow/../oneflow.libs/liboneflow-6c8f8a22.so", at 0x7fb1987f9d3c, in 
> ```

It's here.

**Comment by johnsmith0031** [comment]
Finally it works with model speedup node, I should have put them together at the beginning. Thank you!

**Comment by johnsmith0031** [comment]
Using saving graph node in ComfyUI for SD15 also cause this error:
```
Stack trace (most recent call last) in thread 13290:
   Object "/home/johnsmith/sd_venv_onediff/lib/python3.10/site-packages/oneflow/../oneflow.libs/liboneflow-6c8f8a22.so", at 0x7f47fca66107, in 
   Object "/home/johnsmith/sd_venv_onediff/lib/python3.10/site-packages/oneflow/../oneflow.libs/liboneflow-6c8f8a22.so", at 0x7f47fca65967, in 
   Object "/home/johnsmith/sd_venv_onediff/lib/python3.10/site-packages/oneflow/../oneflow.libs/liboneflow-6c8f8a22.so", at 0x7f47fca611f8, in vm::ThreadCtx::TryReceiveAndRun()
   Object "/home/johnsmith/sd_venv_onediff/lib/python3.10/site-packages/oneflow/../oneflow.libs/liboneflow-6c8f8a22.so", at 0x7f47fca03994, in vm::EpStreamPolicyBase::Run(vm::Instruction*) const
   Object "/home/johnsmith/sd_venv_onediff/lib/python3.10/site-packages/oneflow/../oneflow.libs/liboneflow-6c8f8a22.so", at 0x7f47fca06c97, in vm::Instruction::Compute()
   Object "/home/johnsmith/sd_venv_onediff/lib/python3.10/site-packages/oneflow/../oneflow.libs/liboneflow-6c8f8a22.so", at 0x7f47fca0e078, in vm::OpCallInstructionPolicy::Compute(vm::Instruction*)
   Object "/home/johnsmith/sd_venv_onediff/lib/python3.10/site-packages/oneflow/../oneflow.libs/liboneflow-6c8f8a22.so", at 0x7f47fca0dd49, in 
   Object "/home/johnsmith/sd_venv_onediff/lib/python3.10/site-packages/oneflow/../oneflow.libs/liboneflow-6c8f8a22.so", at 0x7f47fca08e9a, in 
   Object "/home/johnsmith/sd_venv_onediff/lib/python3.10/site-packages/oneflow/../oneflow.libs/liboneflow-6c8f8a22.so", at 0x7f47f41f9d3c, in 
```

**Comment by strint** [comment]
Dos the problem still exists @johnsmith0031

**Comment by johnsmith0031** [comment]
> Dos the problem still exists @johnsmith0031

Still cannot save graph, out of memory

**Comment by strint** [comment]
> > Dos the problem still exists @johnsmith0031
> 
> Still cannot save graph, out of memory

Can you raise a new issue for memory problem, this is out of this isssue.
