### ISSUE TITLE
Trigger NotImplementedError when Inferencing

### ISSUE THREAD

**Issue by uxyz-yang** [siliconflow/onediff#805]
#### A clear and concise description of what the bug is.
Meet a NotImplementedError when Inferencing in ComfyUI with the official "speed up lora" workflow.

#### OS 
Ubuntu 22.04.1 LTS

#### OneDiff git commit id
85d5666

####  OneFlow version info
libibverbs not available, ibv_fork_init skipped
path: ['/home/ubuntu/.local/lib/python3.10/site-packages/oneflow']
version: 0.9.1.dev20240410+cu122
git_commit: b7cd9a4
cmake_build_type: Release
rdma: True
mlir: True
enterprise: False

### How To Reproduce
run official "speed up lora" workflow

### The complete error message
```
ERROR [2024-04-11 16:58:48] /home/ubuntu/.local/lib/python3.10/site-packages/onediff/infer_compiler/oneflow/utils.py:23 - Exception in __call__: e=NotImplementedError("Transform failed of <class 'comfy.ldm.modules.diffusionmodules.openaimodel.UNetModel'>: Transform failed of <class 'torch.nn.modules.container.ModuleList'>: Transform failed of <class 'comfy.ldm.modules.diffusionmodules.openaimodel.TimestepEmbedSequential'>: Transform failed of <class 'comfy.ldm.modules.diffusionmodules.openaimodel.Downsample'>: super(type, obj): obj must be an instance or subtype of type")
ERROR:ONEDIFF:Exception in __call__: e=NotImplementedError("Transform failed of <class 'comfy.ldm.modules.diffusionmodules.openaimodel.UNetModel'>: Transform failed of <class 'torch.nn.modules.container.ModuleList'>: Transform failed of <class 'comfy.ldm.modules.diffusionmodules.openaimodel.TimestepEmbedSequential'>: Transform failed of <class 'comfy.ldm.modules.diffusionmodules.openaimodel.Downsample'>: super(type, obj): obj must be an instance or subtype of type")
WARNING [2024-04-11 16:58:48] /home/ubuntu/.local/lib/python3.10/site-packages/onediff/infer_compiler/oneflow/utils.py:24 - Recompile oneflow module ...
WARNING:ONEDIFF:Recompile oneflow module ...
  0%|          | 0/20 [00:00<?, ?it/s]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onediff/infer_compiler/transform/builtin_transform.py", line 37, in wrapper
    result = dispatcher(first_param, *args, **kwargs)
  File "/usr/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onediff/infer_compiler/transform/builtin_transform.py", line 232, in _
    of_mod = of_mod_cls()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onediff/infer_compiler/transform/builtin_transform.py", line 193, in init
    flow.nn.Module.__init__(self)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/oneflow/nn/modules/module.py", line 150, in __init__
    super().__setattr__("training", True)
TypeError: super(type, obj): obj must be an instance or subtype of type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onediff/infer_compiler/transform/builtin_transform.py", line 37, in wrapper
    result = dispatcher(first_param, *args, **kwargs)
  File "/usr/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onediff/infer_compiler/transform/builtin_transform.py", line 356, in _
    submod = torch2oflow(original_submod, verbose)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onediff/infer_compiler/transform/builtin_transform.py", line 39, in wrapper
    raise NotImplementedError(f"Transform failed of {type(first_param)}: {e}")
NotImplementedError: Transform failed of <class 'comfy.ldm.modules.diffusionmodules.openaimodel.Downsample'>: super(type, obj): obj must be an instance or subtype of type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onediff/infer_compiler/transform/builtin_transform.py", line 37, in wrapper
    result = dispatcher(first_param, *args, **kwargs)
  File "/usr/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onediff/infer_compiler/transform/builtin_transform.py", line 346, in _
    submod = torch2oflow(original_submod, verbose)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onediff/infer_compiler/transform/builtin_transform.py", line 39, in wrapper
    raise NotImplementedError(f"Transform failed of {type(first_param)}: {e}")
NotImplementedError: Transform failed of <class 'comfy.ldm.modules.diffusionmodules.openaimodel.TimestepEmbedSequential'>: Transform failed of <class 'comfy.ldm.modules.diffusionmodules.openaimodel.Downsample'>: super(type, obj): obj must be an instance or subtype of type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onediff/infer_compiler/transform/builtin_transform.py", line 37, in wrapper
    result = dispatcher(first_param, *args, **kwargs)
  File "/usr/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onediff/infer_compiler/transform/builtin_transform.py", line 232, in _
    of_mod = of_mod_cls()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onediff/infer_compiler/transform/builtin_transform.py", line 203, in init
    self._modules[n] = torch2oflow(m)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onediff/infer_compiler/transform/builtin_transform.py", line 39, in wrapper
    raise NotImplementedError(f"Transform failed of {type(first_param)}: {e}")
NotImplementedError: Transform failed of <class 'torch.nn.modules.container.ModuleList'>: Transform failed of <class 'comfy.ldm.modules.diffusionmodules.openaimodel.TimestepEmbedSequential'>: Transform failed of <class 'comfy.ldm.modules.diffusionmodules.openaimodel.Downsample'>: super(type, obj): obj must be an instance or subtype of type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onediff/infer_compiler/oneflow/utils.py", line 21, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onediff/infer_compiler/utils/graph_management_utils.py", line 91, in wrapper
    ret = func(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onediff/infer_compiler/oneflow/deployable_module.py", line 95, in __call__
    dpl_graph = self.get_graph()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onediff/infer_compiler/oneflow/deployable_module.py", line 61, in get_graph
    self._deployable_module_model.oneflow_module,
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onediff/infer_compiler/oneflow/dual_module.py", line 30, in oneflow_module
    self._oneflow_module = torch2oflow(self._torch_module)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onediff/infer_compiler/transform/builtin_transform.py", line 39, in wrapper
    raise NotImplementedError(f"Transform failed of {type(first_param)}: {e}")
NotImplementedError: Transform failed of <class 'comfy.ldm.modules.diffusionmodules.openaimodel.UNetModel'>: Transform failed of <class 'torch.nn.modules.container.ModuleList'>: Transform failed of <class 'comfy.ldm.modules.diffusionmodules.openaimodel.TimestepEmbedSequential'>: Transform failed of <class 'comfy.ldm.modules.diffusionmodules.openaimodel.Downsample'>: super(type, obj): obj must be an instance or subtype of type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onediff/infer_compiler/transform/builtin_transform.py", line 37, in wrapper
    result = dispatcher(first_param, *args, **kwargs)
  File "/usr/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onediff/infer_compiler/transform/builtin_transform.py", line 232, in _
    of_mod = of_mod_cls()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onediff/infer_compiler/transform/builtin_transform.py", line 193, in init
    flow.nn.Module.__init__(self)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/oneflow/nn/modules/module.py", line 150, in __init__
    super().__setattr__("training", True)
TypeError: super(type, obj): obj must be an instance or subtype of type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onediff/infer_compiler/transform/builtin_transform.py", line 37, in wrapper
    result = dispatcher(first_param, *args, **kwargs)
  File "/usr/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onediff/infer_compiler/transform/builtin_transform.py", line 356, in _
    submod = torch2oflow(original_submod, verbose)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onediff/infer_compiler/transform/builtin_transform.py", line 39, in wrapper
    raise NotImplementedError(f"Transform failed of {type(first_param)}: {e}")
NotImplementedError: Transform failed of <class 'comfy.ldm.modules.diffusionmodules.openaimodel.Downsample'>: super(type, obj): obj must be an instance or subtype of type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onediff/infer_compiler/transform/builtin_transform.py", line 37, in wrapper
    result = dispatcher(first_param, *args, **kwargs)
  File "/usr/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onediff/infer_compiler/transform/builtin_transform.py", line 346, in _
    submod = torch2oflow(original_submod, verbose)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onediff/infer_compiler/transform/builtin_transform.py", line 39, in wrapper
    raise NotImplementedError(f"Transform failed of {type(first_param)}: {e}")
NotImplementedError: Transform failed of <class 'comfy.ldm.modules.diffusionmodules.openaimodel.TimestepEmbedSequential'>: Transform failed of <class 'comfy.ldm.modules.diffusionmodules.openaimodel.Downsample'>: super(type, obj): obj must be an instance or subtype of type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onediff/infer_compiler/transform/builtin_transform.py", line 37, in wrapper
    result = dispatcher(first_param, *args, **kwargs)
  File "/usr/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onediff/infer_compiler/transform/builtin_transform.py", line 232, in _
    of_mod = of_mod_cls()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onediff/infer_compiler/transform/builtin_transform.py", line 203, in init
    self._modules[n] = torch2oflow(m)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onediff/infer_compiler/transform/builtin_transform.py", line 39, in wrapper
    raise NotImplementedError(f"Transform failed of {type(first_param)}: {e}")
NotImplementedError: Transform failed of <class 'torch.nn.modules.container.ModuleList'>: Transform failed of <class 'comfy.ldm.modules.diffusionmodules.openaimodel.TimestepEmbedSequential'>: Transform failed of <class 'comfy.ldm.modules.diffusionmodules.openaimodel.Downsample'>: super(type, obj): obj must be an instance or subtype of type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/ubuntu/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/ubuntu/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/ubuntu/ComfyUI/nodes.py", line 1368, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "/home/ubuntu/ComfyUI/nodes.py", line 1338, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "/home/ubuntu/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/sample_error_enhancer.py", line 22, in informative_sample
    raise e
  File "/home/ubuntu/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/sample_error_enhancer.py", line 9, in informative_sample
    return original_sample(*args, **kwargs)  # This code helps interpret error messages that occur within exceptions but does not have any impact on other operations.
  File "/home/ubuntu/ComfyUI/comfy/sample.py", line 100, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/home/ubuntu/ComfyUI/comfy/samplers.py", line 713, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/home/ubuntu/ComfyUI/comfy/samplers.py", line 618, in sample
    samples = sampler.sample(model_wrap, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "/home/ubuntu/ComfyUI/comfy/samplers.py", line 557, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/ComfyUI/comfy/k_diffusion/sampling.py", line 137, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/ComfyUI/comfy/samplers.py", line 281, in forward
    out = self.inner_model(x, sigma, cond=cond, uncond=uncond, cond_scale=cond_scale, model_options=model_options, seed=seed)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/ComfyUI/comfy/samplers.py", line 271, in forward
    return self.apply_model(*args, **kwargs)
  File "/home/ubuntu/ComfyUI/comfy/samplers.py", line 268, in apply_model
    out = sampling_function(self.inner_model, x, timestep, uncond, cond, cond_scale, model_options=model_options, seed=seed)
  File "/home/ubuntu/ComfyUI/comfy/samplers.py", line 248, in sampling_function
    cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
  File "/home/ubuntu/ComfyUI/custom_nodes/onediff_comfy_nodes/modules/sd_hijack_utils.py", line 41, in <lambda>
    lambda *args, **kwargs: self(*args, **kwargs),
  File "/home/ubuntu/ComfyUI/custom_nodes/onediff_comfy_nodes/modules/sd_hijack_utils.py", line 57, in __call__
    return self.__sub_func(self.__orig_func, *args, **kwargs)
  File "/home/ubuntu/ComfyUI/custom_nodes/onediff_comfy_nodes/modules/hijack_samplers.py", line 126, in new_calc_cond_uncond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "/home/ubuntu/ComfyUI/comfy/model_base.py", line 91, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onediff/infer_compiler/utils/online_quantization_utils.py", line 48, in wrapper
    output = func(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onediff/infer_compiler/utils/args_tree_util.py", line 50, in wrapper
    output = func(self, *mapped_args, **mapped_kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onediff/infer_compiler/oneflow/utils.py", line 27, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onediff/infer_compiler/utils/graph_management_utils.py", line 91, in wrapper
    ret = func(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onediff/infer_compiler/oneflow/deployable_module.py", line 95, in __call__
    dpl_graph = self.get_graph()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onediff/infer_compiler/oneflow/deployable_module.py", line 61, in get_graph
    self._deployable_module_model.oneflow_module,
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onediff/infer_compiler/oneflow/dual_module.py", line 30, in oneflow_module
    self._oneflow_module = torch2oflow(self._torch_module)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onediff/infer_compiler/transform/builtin_transform.py", line 39, in wrapper
    raise NotImplementedError(f"Transform failed of {type(first_param)}: {e}")
NotImplementedError: Transform failed of <class 'comfy.ldm.modules.diffusionmodules.openaimodel.UNetModel'>: Transform failed of <class 'torch.nn.modules.container.ModuleList'>: Transform failed of <class 'comfy.ldm.modules.diffusionmodules.openaimodel.TimestepEmbedSequential'>: Transform failed of <class 'comfy.ldm.modules.diffusionmodules.openaimodel.Downsample'>: super(type, obj): obj must be an instance or subtype of type
```

**Comment by ccssu** [comment]
可以先使用 
```shell
cd onediff && git checkout b9b79215ebec524dde473f5dd7a32c1b45c569b4 
pip install -e .
```
下图是工作流：
![workflow (5)](https://github.com/siliconflow/onediff/assets/109639975/c0ba46d4-b331-42f3-a993-fcf4fb61a61f)

相关环境：
ComfyUI:
```
commit fd7c63668080f8c2eb56edffeef028aa3932e0fe (HEAD -> master)
Author: comfyanonymous <comfyanonymous@protonmail.com>
Date:   Wed Apr 10 20:29:35 2024 -0400
```
