### ISSUE TITLE
AttributeError: 'OneflowGraph' object has no attribute '_input_op_names'

### ISSUE THREAD

**Issue by uxyz-yang** [siliconflow/onediff#806]
#### A clear and concise description of what the bug is.
Onediff was working well after fixing issue #805 according to the reply resolution. 
However, it broke again without any operation after a while.
The errors are different.

#### OS 
Ubuntu 22.04.1 LTS

#### OneDiff git commit id
b9b7921

####  OneFlow version info
libibverbs not available, ibv_fork_init skipped
path: ['/home/ubuntu/.local/lib/python3.10/site-packages/oneflow']
version: 0.9.1.dev20240410+cu122
git_commit: b7cd9a4
cmake_build_type: Release
rdma: True
mlir: True
enterprise: False

### How To Reproduce
Steps to reproduce the behavior(code or script):
The attachment issue #805:
https://github.com/siliconflow/onediff/files/14944052/workflow.json

### The complete error message
```
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/home/ubuntu/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/ubuntu/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/ubuntu/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/ubuntu/ComfyUI/nodes.py", line 1368, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "/home/ubuntu/ComfyUI/nodes.py", line 1338, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "/home/ubuntu/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/sample_error_enhancer.py", line 9, in informative_sample
    return original_sample(*args, **kwargs)  # This code helps interpret error messages that occur within exceptions but does not have any impact on other operations.
  File "/home/ubuntu/ComfyUI/comfy/sample.py", line 100, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/home/ubuntu/ComfyUI/comfy/samplers.py", line 713, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/home/ubuntu/ComfyUI/comfy/samplers.py", line 618, in sample
    samples = sampler.sample(model_wrap, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "/home/ubuntu/ComfyUI/comfy/samplers.py", line 557, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/ComfyUI/comfy/k_diffusion/sampling.py", line 137, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/ComfyUI/comfy/samplers.py", line 281, in forward
    out = self.inner_model(x, sigma, cond=cond, uncond=uncond, cond_scale=cond_scale, model_options=model_options, seed=seed)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/ComfyUI/comfy/samplers.py", line 271, in forward
    return self.apply_model(*args, **kwargs)
  File "/home/ubuntu/ComfyUI/comfy/samplers.py", line 268, in apply_model
    out = sampling_function(self.inner_model, x, timestep, uncond, cond, cond_scale, model_options=model_options, seed=seed)
  File "/home/ubuntu/ComfyUI/comfy/samplers.py", line 248, in sampling_function
    cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
  File "/home/ubuntu/ComfyUI/custom_nodes/onediff_comfy_nodes/modules/sd_hijack_utils.py", line 41, in <lambda>
    lambda *args, **kwargs: self(*args, **kwargs),
  File "/home/ubuntu/ComfyUI/custom_nodes/onediff_comfy_nodes/modules/sd_hijack_utils.py", line 57, in __call__
    return self.__sub_func(self.__orig_func, *args, **kwargs)
  File "/home/ubuntu/ComfyUI/custom_nodes/onediff_comfy_nodes/modules/hijack_samplers.py", line 126, in new_calc_cond_uncond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "/home/ubuntu/ComfyUI/comfy/model_base.py", line 91, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onediff/infer_compiler/utils/online_quantization_utils.py", line 48, in wrapper
    output = func(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/onediff/infer_compiler/utils/args_tree_util.py", line 42, in wrapper
    count = len(self._deployable_module_dpl_graph._input_op_names)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 2155, in __getattr__
    raise AttributeError(
AttributeError: 'OneflowGraph' object has no attribute '_input_op_names'
```

**Comment by ccssu** [comment]
这个错误是由于 使用 vae speedup 触发 AssertionError: **runtime_state_dict_to is only supported in the enterprise edition**. 
从而导致的 生成 graph 对象不正常 AttributeError: 'OneflowGraph' object has no attribute '_input_op_names'。

<details close>
<summary> 全部报错信息 </summary>

```
==> function onediff.infer_compiler.utils.graph_management_utils.generate_graph_file_name  try to run...
Convert <class 'comfy.ldm.modules.diffusionmodules.openaimodel.UNetModel'> ...
Convert <class 'comfy.ldm.modules.diffusionmodules.openaimodel.UNetModel'> done!
generate_graph_file_name run time 3.6249234676361084 seconds
<== function generate_graph_file_name finish run.

Building a graph for <class 'register_comfy.openaimodel.UNetModel'> ...
==> function onediff.infer_compiler.oneflow.graph.load_graph  try to run...
load_graph cuda mem before 8858.0 MB
load_graph host mem before 1763.0 MB
  0%|                                                                     | 0/20 [00:04<?, ?it/s]
!!! Exception during processing !!!
Traceback (most recent call last):
  File "/data/home/fengwen/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/data/home/fengwen/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/data/home/fengwen/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/data/home/fengwen/ComfyUI/nodes.py", line 1344, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "/data/home/fengwen/ComfyUI/nodes.py", line 1314, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "/data/home/fengwen/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved/animatediff/sampling.py", line 267, in motion_sample
    return orig_comfy_sample(model, noise, *args, **kwargs)
  File "/data/home/fengwen/ComfyUI/comfy/sample.py", line 37, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/data/home/fengwen/ComfyUI/comfy/samplers.py", line 755, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/data/home/fengwen/ComfyUI/comfy/samplers.py", line 657, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "/data/home/fengwen/ComfyUI/comfy/samplers.py", line 644, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "/data/home/fengwen/ComfyUI/comfy/samplers.py", line 623, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "/data/home/fengwen/ComfyUI/comfy/samplers.py", line 534, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "/data/home/fengwen/miniconda3/envs/py310/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/home/fengwen/ComfyUI/comfy/k_diffusion/sampling.py", line 137, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "/data/home/fengwen/ComfyUI/comfy/samplers.py", line 272, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "/data/home/fengwen/ComfyUI/comfy/samplers.py", line 610, in __call__
    return self.predict_noise(*args, **kwargs)
  File "/data/home/fengwen/ComfyUI/comfy/samplers.py", line 613, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "/data/home/fengwen/ComfyUI/comfy/samplers.py", line 258, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
  File "/data/home/fengwen/ComfyUI/comfy/samplers.py", line 218, in calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "/data/home/fengwen/ComfyUI/comfy/model_base.py", line 97, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "/data/home/fengwen/miniconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/home/fengwen/miniconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1561, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/fengwen/worksplace/onediff/src/onediff/infer_compiler/utils/online_quantization_utils.py", line 48, in wrapper
    output = func(self, *args, **kwargs)
  File "/home/fengwen/worksplace/onediff/src/onediff/infer_compiler/utils/args_tree_util.py", line 50, in wrapper
    output = func(self, *mapped_args, **mapped_kwargs)
  File "/home/fengwen/worksplace/onediff/src/onediff/infer_compiler/oneflow/utils.py", line 18, in wrapper
    return func(self, *args, **kwargs)
  File "/home/fengwen/worksplace/onediff/src/onediff/infer_compiler/utils/graph_management_utils.py", line 87, in wrapper
    handle_graph_loading()
  File "/home/fengwen/worksplace/onediff/src/onediff/infer_compiler/utils/graph_management_utils.py", line 67, in handle_graph_loading
    self.load_graph(graph_file, torch2oflow(graph_device))
  File "/home/fengwen/worksplace/onediff/src/onediff/infer_compiler/oneflow/deployable_module.py", line 149, in load_graph
    self.get_graph().load_graph(file_path, device, run_warmup)
  File "/home/fengwen/worksplace/onediff/src/onediff/infer_compiler/utils/cost_util.py", line 62, in clocked
    out = func(*args, **kwargs)
  File "/home/fengwen/worksplace/onediff/src/onediff/infer_compiler/oneflow/graph.py", line 26, in load_graph
    state_dict = flow.nn.Graph.runtime_state_dict_to(state_dict, device)
  File "/data/home/fengwen/miniconda3/envs/py310/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 1375, in runtime_state_dict_to
    assert (
AssertionError: runtime_state_dict_to is only supported in the enterprise edition.

Prompt executed in 24.41 seconds
  0%|                                                                     | 0/20 [00:00<?, ?it/s]
!!! Exception during processing !!!
Traceback (most recent call last):
  File "/data/home/fengwen/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/data/home/fengwen/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/data/home/fengwen/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/data/home/fengwen/ComfyUI/nodes.py", line 1344, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "/data/home/fengwen/ComfyUI/nodes.py", line 1314, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "/data/home/fengwen/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved/animatediff/sampling.py", line 267, in motion_sample
    return orig_comfy_sample(model, noise, *args, **kwargs)
  File "/data/home/fengwen/ComfyUI/comfy/sample.py", line 37, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/data/home/fengwen/ComfyUI/comfy/samplers.py", line 755, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/data/home/fengwen/ComfyUI/comfy/samplers.py", line 657, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "/data/home/fengwen/ComfyUI/comfy/samplers.py", line 644, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "/data/home/fengwen/ComfyUI/comfy/samplers.py", line 623, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "/data/home/fengwen/ComfyUI/comfy/samplers.py", line 534, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "/data/home/fengwen/miniconda3/envs/py310/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/home/fengwen/ComfyUI/comfy/k_diffusion/sampling.py", line 137, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "/data/home/fengwen/ComfyUI/comfy/samplers.py", line 272, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "/data/home/fengwen/ComfyUI/comfy/samplers.py", line 610, in __call__
    return self.predict_noise(*args, **kwargs)
  File "/data/home/fengwen/ComfyUI/comfy/samplers.py", line 613, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "/data/home/fengwen/ComfyUI/comfy/samplers.py", line 258, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
  File "/data/home/fengwen/ComfyUI/comfy/samplers.py", line 218, in calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "/data/home/fengwen/ComfyUI/comfy/model_base.py", line 97, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "/data/home/fengwen/miniconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/home/fengwen/miniconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1561, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/fengwen/worksplace/onediff/src/onediff/infer_compiler/utils/online_quantization_utils.py", line 48, in wrapper
    output = func(self, *args, **kwargs)
  File "/home/fengwen/worksplace/onediff/src/onediff/infer_compiler/utils/args_tree_util.py", line 42, in wrapper
    count = len(self._deployable_module_dpl_graph._input_op_names)
  File "/data/home/fengwen/miniconda3/envs/py310/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 2155, in __getattr__
    raise AttributeError(
AttributeError: 'OneflowGraph' object has no attribute '_input_op_names'

Prompt executed in 0.03 seconds
```
</details>

## 工作流
![workflow (7)](https://github.com/siliconflow/onediff/assets/109639975/6be883b8-96a9-486a-8e02-d4b5d8bbae64)

## 相关环境：
python 3.10 
```shell
python -m oneflow --doctor
path: ['/data/home/fengwen/miniconda3/envs/py310/lib/python3.10/site-packages/oneflow']
version: 0.9.1.dev20240411+cu121
git_commit: b7cd9a4
cmake_build_type: Release
rdma: True
mlir: True
enterprise: False
```

**Comment by ccssu** [comment]
已修复，请参考如下指令重新安装： @uxyz-yang 
```shell
# install oneflow
pip uninstall oneflow -y && python3 -m pip install -U --pre oneflow -f https://oneflow-pro.oss-cn-beijing.aliyuncs.com/branch/community/cu121 

# onediff
cd onediff && git pull && pip install -e .

# install onediff_comfy_nodes
cp -r onediff/onediff_comfy_nodes ComfyUI/custom_nodes/
```

测试工作流：
![workflow (8)](https://github.com/siliconflow/onediff/assets/109639975/4dbe98f9-8234-4b02-b2b6-3c98292dd9ae)

### 测试环境：
```shell
Python 3.10.13

$ python -m oneflow --doctor

path: ['/data/home/fengwen/miniconda3/envs/py310/lib/python3.10/site-packages/oneflow']
version: 0.9.1.dev20240411+cu121
git_commit: 931ca52
cmake_build_type: Release
rdma: True
mlir: True
enterprise: False

onediff: 
    commit e4d56a046024194597068c73ef8c6e160e2cd371 (HEAD -> main, origin/main, origin/HEAD)
    Date:   Thu Apr 11 16:29:19 2024 +0800

comfyui: 
    commit fd7c63668080f8c2eb56edffeef028aa3932e0fe (HEAD -> master)
    Date:   Wed Apr 10 20:29:35 2024 -0400

```
