### ISSUE TITLE
转换sam的ImageEncoderViT模型失败

### ISSUE THREAD

**Issue by zhangvia** [siliconflow/onediff#824]
#### OneDiff git commit id
87eb97f
####  OneFlow version info
Run `python -m oneflow --doctor` and paste it here.
```path: ['/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/oneflow']
version: 0.9.1.dev20240413+cu118
git_commit: 67341c9
cmake_build_type: Release
rdma: True
mlir: True
enterprise: False
```
### How To Reproduce
Steps to reproduce the behavior(code or script):
```
from segment_anything.modeling import ImageEncoderViT
from onediff.infer_compiler import oneflow_compile
import torch

model = ImageEncoderViT()
input = torch.randn(1,3,1024,1024)
model = oneflow_compile(model)
output = model(input)

```
### The complete error message
```
ERROR [2024-04-17 05:56:53] /media/74nvme/research/onediff/src/onediff/infer_compiler/oneflow/utils.py:23 - Exception in forward: e=NotImplementedError("Transform failed of <class 'segment_anything.modeling.image_encoder.ImageEncoderViT'>: super(type, obj): obj must be an instance or subtype of type")
WARNING [2024-04-17 05:56:53] /media/74nvme/research/onediff/src/onediff/infer_compiler/oneflow/utils.py:24 - Recompile oneflow module ...
Traceback (most recent call last):
  File "/media/74nvme/research/onediff/src/onediff/infer_compiler/transform/builtin_transform.py", line 38, in wrapper
    result = dispatcher(first_param, *args, **kwargs)
  File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/functools.py", line 878, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/media/74nvme/research/onediff/src/onediff/infer_compiler/transform/builtin_transform.py", line 238, in _
    of_mod = of_mod_cls()
  File "/media/74nvme/research/onediff/src/onediff/infer_compiler/transform/builtin_transform.py", line 199, in init
    flow.nn.Module.__init__(self)
  File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/oneflow/nn/modules/module.py", line 150, in __init__
    super().__setattr__("training", True)
TypeError: super(type, obj): obj must be an instance or subtype of type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/74nvme/research/onediff/src/onediff/infer_compiler/oneflow/utils.py", line 21, in wrapper
    return func(self, *args, **kwargs)
  File "/media/74nvme/research/onediff/src/onediff/infer_compiler/utils/graph_management_utils.py", line 91, in wrapper
    ret = func(self, *args, **kwargs)
  File "/media/74nvme/research/onediff/src/onediff/infer_compiler/oneflow/deployable_module.py", line 97, in forward
    dpl_graph = self.get_graph()
  File "/media/74nvme/research/onediff/src/onediff/infer_compiler/oneflow/deployable_module.py", line 63, in get_graph
    self._deployable_module_model.oneflow_module,
  File "/media/74nvme/research/onediff/src/onediff/infer_compiler/oneflow/dual_module.py", line 30, in oneflow_module
    self._oneflow_module = torch2oflow(self._torch_module)
  File "/media/74nvme/research/onediff/src/onediff/infer_compiler/transform/builtin_transform.py", line 40, in wrapper
    raise NotImplementedError(f"Transform failed of {type(first_param)}: {e}")
NotImplementedError: Transform failed of <class 'segment_anything.modeling.image_encoder.ImageEncoderViT'>: super(type, obj): obj must be an instance or subtype of type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/74nvme/research/onediff/src/onediff/infer_compiler/transform/builtin_transform.py", line 38, in wrapper
    result = dispatcher(first_param, *args, **kwargs)
  File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/functools.py", line 878, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/media/74nvme/research/onediff/src/onediff/infer_compiler/transform/builtin_transform.py", line 238, in _
    of_mod = of_mod_cls()
  File "/media/74nvme/research/onediff/src/onediff/infer_compiler/transform/builtin_transform.py", line 199, in init
    flow.nn.Module.__init__(self)
  File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/oneflow/nn/modules/module.py", line 150, in __init__
    super().__setattr__("training", True)
TypeError: super(type, obj): obj must be an instance or subtype of type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/media/74nvme/software/miniconda3/envs/stable-fast/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1561, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/media/74nvme/research/onediff/src/onediff/infer_compiler/utils/online_quantization_utils.py", line 48, in wrapper
    output = func(self, *args, **kwargs)
  File "/media/74nvme/research/onediff/src/onediff/infer_compiler/utils/args_tree_util.py", line 50, in wrapper
    output = func(self, *mapped_args, **mapped_kwargs)
  File "/media/74nvme/research/onediff/src/onediff/infer_compiler/oneflow/utils.py", line 27, in wrapper
    return func(self, *args, **kwargs)
  File "/media/74nvme/research/onediff/src/onediff/infer_compiler/utils/graph_management_utils.py", line 91, in wrapper
    ret = func(self, *args, **kwargs)
  File "/media/74nvme/research/onediff/src/onediff/infer_compiler/oneflow/deployable_module.py", line 97, in forward
    dpl_graph = self.get_graph()
  File "/media/74nvme/research/onediff/src/onediff/infer_compiler/oneflow/deployable_module.py", line 63, in get_graph
    self._deployable_module_model.oneflow_module,
  File "/media/74nvme/research/onediff/src/onediff/infer_compiler/oneflow/dual_module.py", line 30, in oneflow_module
    self._oneflow_module = torch2oflow(self._torch_module)
  File "/media/74nvme/research/onediff/src/onediff/infer_compiler/transform/builtin_transform.py", line 40, in wrapper
    raise NotImplementedError(f"Transform failed of {type(first_param)}: {e}")
NotImplementedError: Transform failed of <class 'segment_anything.modeling.image_encoder.ImageEncoderViT'>: super(type, obj): obj must be an instance or subtype of type

```

**Comment by strint** [comment]
> use oneflow_compile to compile the ImageEncoderViT model

Please wait for onediff 1.1.

oneflow_compile is not a very general API to compile other models for now.

@zhangvia

**Comment by zhangvia** [comment]
> > use oneflow_compile to compile the ImageEncoderViT model
> 
> Please wait for onediff 1.1.
> 
> oneflow_compile is not a very general API to compile other models for now.
> 
> @zhangvia

got it. there is another question i want to know. the newest version of oneflow is 1.0.0 in github repo changelog. but there is no prebuilt version 1.0.0 in https://github.com/siliconflow/oneflow_releases/releases/expanded_assets/, right? and besides, when i install oneflow use ```python3 -m pip install -U --pre oneflow -f https://github.com/siliconflow/oneflow_releases/releases/expanded_assets/community_cu118```, there is compile_from_torch method sometimes, and sometimes there is not. i don't know why

**Comment by strint** [comment]
> got it. there is another question i want to know. the newest version of oneflow is 1.0.0 in github repo changelog. 

OneDiff is using a special oneflow build by onediff team, let's call it oneflow4onediff. It's different with oneflow 1.0.0.

oneflow4onediff is here: https://github.com/siliconflow/onediff?tab=readme-ov-file#1-install-oneflow

**Comment by zhangvia** [comment]
but there is also no prebuilt verison v1.0.0 in https://oneflow-staging.oss-cn-beijing.aliyuncs.com/branch/master/cu118 or https://pypi.tuna.tsinghua.edu.cn/simple. the version 1.0.0 can only be installed from source?

besides, what is the difference between the compile_from_torch in oneflow v1.0.0 and onediff ?

**Comment by strint** [comment]
> besides, what is the difference between the compile_from_torch in oneflow v1.0.0 and onediff ?

compile_from_torch is absorbed form onediff infer_compiler and compile_from_torch is trying to be able to compile more torch models then onediff(which focuses on diffusion models)

**Comment by jackalcooper** [comment]
> verison v1.0.0

verison v1.0.0 is onediff's version, not oneflow's. It would work by installing these nightly builds of oneflow which including dates like `dev20240415`

**Comment by zhangvia** [comment]
> verison v1.0.0 is onediff's version, not oneflow's. It would work by installing these nightly builds of oneflow which including dates like `dev20240415`

i think the oneflow also has version 1.0.0 ![image](https://github.com/siliconflow/onediff/assets/38352569/ea36d4e7-0e61-47f6-aeba-2febe50a7ac5)

**Comment by strint** [comment]
> but there is also no prebuilt verison v1.0.0 in https://oneflow-staging.oss-cn-beijing.aliyuncs.com/branch/master/cu118 or https://pypi.tuna.tsinghua.edu.cn/simple. the version 1.0.0 can only be installed from source?

Yes.

But if you are using onediff, you must install oneflow from here:  https://github.com/siliconflow/onediff?tab=readme-ov-file#1-install-oneflow
