### ISSUE TITLE
can't install in comfyui

### ISSUE THREAD

**Issue by Uniky** [siliconflow/onediff#827]
I have already installed oneflow following this guide
![image](https://github.com/siliconflow/onediff/assets/24896456/780e1734-0f5f-4cc8-b96a-2981035d53bb)
but I got the following error when loading:
Traceback (most recent call last):
  File "E:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\onediff_comfy_nodes\__init__.py", line 2, in <module>
    from ._config import _USE_UNET_INT8
  File "E:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\onediff_comfy_nodes\_config.py", line 15, in <module>
    import register_comfy  # load plugins
  File "E:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\onediff_comfy_nodes\infer_compiler_registry\register_comfy\__init__.py", line 1, in <module>
    from onediff.infer_compiler import register
  File "D:\Soft\onediff\src\onediff\infer_compiler\__init__.py", line 3, in <module>
    import oneflow as flow
  File "E:\StableDiffusion\ComfyUI_windows_portable\python_embeded\lib\site-packages\oneflow\__init__.py", line 21, in <module>
    raise RuntimeError("This package is a placeholder. Please install oneflow following the instructions in https://github.com/Oneflow-Inc/oneflow#install-oneflow")
RuntimeError: This package is a placeholder. Please install oneflow following the instructions in https://github.com/Oneflow-Inc/oneflow#install-oneflow

Cannot import E:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\onediff_comfy_nodes module for custom nodes: This package is a placeholder. Please install oneflow following the instructions in https://github.com/Oneflow-Inc/oneflow#install-oneflow

**Comment by ssljr** [comment]
I have the same problem. Does anyone know how to solve this issue?

**Comment by nono-Sang** [comment]
On Linux, this may be caused by the Python version. You can refer to https://github.com/siliconflow/onediff/issues/765.

**Comment by strint** [comment]
> Traceback (most recent call last): File "E:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1864, in load_custom_node

@Uniky It's seems that you are run this on windows?
https://github.com/siliconflow/onediff?tab=readme-ov-file#os-and-gpu-compatibility

**Comment by doombeaker** [comment]
If you need to run OneDiff on Windows, you should use the WSL2 which can be referred to: https://github.com/siliconflow/onediff/wiki/Run-OneDiff-on-Windows-by-WSL2
