### ISSUE TITLE
image-to-image sdxl light

### ISSUE THREAD

**Issue by Muawiz-Umar** [siliconflow/onediff#841]
### Describe the bug
I have the baseline text_to_image_sdxl_light.py working (using lora checkpoint). I used same script instead of using text-to-image pipeline of diffusers, i am using image-to-image sdxl light pipeline (using lora checkpoint)

### Your environment
ubuntu

####  OneFlow version info
version: 0.9.1.dev20240411+cu118
git_commit: 67341c9
cmake_build_type: Release
rdma: True
mlir: True
enterprise: True

### How To Reproduce
add `StableDiffusionXLImg2ImgPipeline` in text_to_image_sdxl_light.py  (using lora checkpoint)

print("warm-up graph...")
image = self.pipe(
            prompt=prompt,
            image=image_data,
            num_inference_steps=steps,
            strength=strength,
            guidance_scale=0,
            generator=generator,
            output_type="pil"
        ).images[0]

### The complete error message
```
[ERROR](GRAPH:OneflowGraph_3:OneflowGraph) building graph got error.
ERROR [2024-04-25 10:12:01] /home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/onediff/infer_compiler/oneflow/utils.py:23 - Exception in forward: e=AttributeError("'MODULE' 'ProxyModule' object 'model.down_blocks.1.attentions.0' in nn.Graph has no attribute 'caption_projection'")
WARNING [2024-04-25 10:12:01] /home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/onediff/infer_compiler/oneflow/utils.py:24 - Recompile oneflow module ...
[ERROR](GRAPH:OneflowGraph_4:OneflowGraph) building graph got error.
Traceback (most recent call last):
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/onediff/infer_compiler/oneflow/utils.py", line 21, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/onediff/infer_compiler/utils/graph_management_utils.py", line 91, in wrapper
    ret = func(self, *args, **kwargs)
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/onediff/infer_compiler/oneflow/deployable_module.py", line 99, in forward
    output = dpl_graph(*args, **kwargs)
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 295, in __call__
    self._compile(*args, **kwargs)
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 861, in _compile
    return self._dynamic_input_graph_cache._compile(*args, **kwargs)
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/oneflow/nn/graph/cache.py", line 121, in _compile
    return graph._compile(*args, **kwargs)
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 865, in _compile
    return self._compile_new(*args, **kwargs)
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 884, in _compile_new
    _, eager_outputs = self.build_graph(*args, **kwargs)
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 1429, in build_graph
    outputs = self.__build_graph(*args, **kwargs)
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 1577, in __build_graph
    outputs = self.build(*lazy_args, **lazy_kwargs)
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/onediff/infer_compiler/oneflow/graph.py", line 19, in build
    return self.model(*args, **kwargs)
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 188, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 238, in __block_forward
    result = unbound_forward_of_module_instance(self, *args, **kwargs)
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/infer_compiler_registry/register_diffusers/unet_2d_condition_oflow.py", line 358, in forward
    sample, res_samples = downsample_block(
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 188, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 238, in __block_forward
    result = unbound_forward_of_module_instance(self, *args, **kwargs)
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/diffusers/models/unets/unet_2d_blocks.py", line 1288, in forward
    hidden_states = attn(
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 188, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 238, in __block_forward
    result = unbound_forward_of_module_instance(self, *args, **kwargs)
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/infer_compiler_registry/register_diffusers/transformer_2d_oflow.py", line 1062, in forward
    if self.caption_projection is not None:
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 514, in __getattr__
    raise AttributeError(
AttributeError: 'MODULE' 'ProxyModule' object 'model.down_blocks.1.attentions.0' in nn.Graph has no attribute 'caption_projection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/umar_muawiz/oneflow/test_img2img_sdxl_light.py", line 135, in <module>
    res  = obj.predict(prompt=prompt, image_data=image_data)
  File "/home/ubuntu/umar_muawiz/oneflow/test_img2img_sdxl_light.py", line 117, in predict
    image = self.pipe(
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py", line 1364, in __call__
    noise_pred = self.unet(
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1561, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/onediff/infer_compiler/utils/online_quantization_utils.py", line 48, in wrapper
    output = func(self, *args, **kwargs)
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/onediff/infer_compiler/utils/args_tree_util.py", line 50, in wrapper
    output = func(self, *mapped_args, **mapped_kwargs)
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/onediff/infer_compiler/oneflow/utils.py", line 27, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/onediff/infer_compiler/utils/graph_management_utils.py", line 91, in wrapper
    ret = func(self, *args, **kwargs)
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/onediff/infer_compiler/oneflow/deployable_module.py", line 99, in forward
    output = dpl_graph(*args, **kwargs)
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 295, in __call__
    self._compile(*args, **kwargs)
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 861, in _compile
    return self._dynamic_input_graph_cache._compile(*args, **kwargs)
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/oneflow/nn/graph/cache.py", line 121, in _compile
    return graph._compile(*args, **kwargs)
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 865, in _compile
    return self._compile_new(*args, **kwargs)
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 884, in _compile_new
    _, eager_outputs = self.build_graph(*args, **kwargs)
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 1429, in build_graph
    outputs = self.__build_graph(*args, **kwargs)
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 1577, in __build_graph
    outputs = self.build(*lazy_args, **lazy_kwargs)
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/onediff/infer_compiler/oneflow/graph.py", line 19, in build
    return self.model(*args, **kwargs)
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 188, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 238, in __block_forward
    result = unbound_forward_of_module_instance(self, *args, **kwargs)
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/infer_compiler_registry/register_diffusers/unet_2d_condition_oflow.py", line 358, in forward
    sample, res_samples = downsample_block(
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 188, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 238, in __block_forward
    result = unbound_forward_of_module_instance(self, *args, **kwargs)
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/diffusers/models/unets/unet_2d_blocks.py", line 1288, in forward
    hidden_states = attn(
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 188, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 238, in __block_forward
    result = unbound_forward_of_module_instance(self, *args, **kwargs)
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/infer_compiler_registry/register_diffusers/transformer_2d_oflow.py", line 1062, in forward
    if self.caption_projection is not None:
  File "/home/ubuntu/umar_muawiz/oneflow/enterprise_oneflow/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 514, in __getattr__
    raise AttributeError(
AttributeError: 'MODULE' 'ProxyModule' object 'model.down_blocks.1.attentions.0' in nn.Graph has no attribute 'caption_projection'
```

**Comment by strint** [comment]
@Muawiz-Umar Please refer to this issue: https://github.com/siliconflow/onediff/issues/925
