### ISSUE TITLE
During execution, the script keeps adjusting the size of the output image, resulting in OOM of the graphics card

### ISSUE THREAD

**Issue by lijunliangTG** [siliconflow/onediff#848]
#### A clear and concise description of what the bug is.
Load and execute an image-to-image conversion model based on Stable Diffusion XL, accelerated using OneDiff. During execution, the script constantly resizes the output image, and may gradually increase the memory footprint due to repetitive model loading and processing within the loop.

#### OS 
Ubuntu 20.04.4 LTS

#### OneDiff git commit id
6077d115

####  OneFlow version info
Run `python -m oneflow --doctor` and paste it here.
(sd2) lijunliang@oneflow-25:~/project/onediff$ python -m oneflow --doctor
path: ['/data/home/lijunliang/anaconda3/envs/sd2/lib/python3.10/site-packages/oneflow']
version: 0.9.1.dev20240428+cu122
git_commit: 665bcf8
cmake_build_type: Release
rdma: True
mlir: True
enterprise: True

### How To Reproduce
Steps to reproduce the behavior(code or script):
```
import os
import argparse
import time

import torch
from safetensors.torch import load_file
from diffusers import StableDiffusionXLImg2ImgPipeline
from onediffx import compile_pipe, compiler_config, save_pipe, load_pipe
from huggingface_hub import hf_hub_download
from diffusers.utils import load_image
import oneflow
try:
    USE_PEFT_BACKEND = diffusers.utils.USE_PEFT_BACKEND
except Exception as e:
    USE_PEFT_BACKEND = False


def main(args):

    OUTPUT_TYPE = "pil"

    path = args.src_img
    print(f"path {path}")
    init_image = load_image(path).convert("RGB")

    n_steps = int(args.cpkt[len("sdxl_lightning_") : len("sdxl_lightning_") + 1])

    is_lora_cpkt = "lora" in args.cpkt

    if args.onediff_compile:
        from onediff.schedulers import EulerDiscreteScheduler
    else:
        from diffusers import EulerDiscreteScheduler

    if is_lora_cpkt:
        if not USE_PEFT_BACKEND:
            print("PEFT backend is required for load_lora_weights")
            exit(0)
        pipe = StableDiffusionXLImg2ImgPipeline.from_pretrained(
            args.base, torch_dtype=torch.float16, variant="fp16"
        ).to("cuda")
        if os.path.isfile(os.path.join(args.repo, args.cpkt)):
            pipe.load_lora_weights(os.path.join(args.repo, args.cpkt))
        else:
            pipe.load_lora_weights(hf_hub_download(args.repo, args.cpkt))
        pipe.fuse_lora()
    else:
        from diffusers import UNet2DConditionModel

        unet = UNet2DConditionModel.from_config(args.base, subfolder="unet").to(
            "cuda", torch.float16
        )
        if os.path.isfile(os.path.join(args.repo, args.cpkt)):
            unet.load_state_dict(
                load_file(os.path.join(args.repo, args.cpkt), device="cuda")
            )
        else:
            unet.load_state_dict(
                load_file(hf_hub_download(args.repo, args.cpkt), device="cuda")
            )
        pipe = StableDiffusionXLImg2ImgPipeline.from_pretrained(
            args.base, unet=unet, torch_dtype=torch.float16, variant="fp16"
        ).to("cuda")

    pipe.scheduler = EulerDiscreteScheduler.from_config(
        pipe.scheduler.config, timestep_spacing="trailing"
    )

    if pipe.vae.dtype == torch.float16 and pipe.vae.config.force_upcast:
        pipe.upcast_vae()

    # Compile the pipeline
    if args.onediff_compile:
        pipe = compile_pipe(pipe,)

        if args.load_graph:
            print("Loading graphs...")
            import pdb;pdb.set_trace()
            load_pipe(pipe, args.load_graph_dir)

    print("Warmup with running graphs...")
    torch.manual_seed(args.seed)
    image = pipe(
        prompt=args.prompt,
        image = init_image,
        height=args.height,
        width=args.width,
        num_inference_steps=n_steps,
        guidance_scale=0,
        output_type=OUTPUT_TYPE,
    ).images[0]


    # Normal run
    print("Normal run...")
    torch.manual_seed(args.seed)
    start_t = time.time()
    image = pipe(
        prompt=args.prompt,
        image = init_image,
        height=args.height,
        width=args.width,
        num_inference_steps=n_steps,
        guidance_scale=0,
        output_type=OUTPUT_TYPE,
    ).images

    end_t = time.time()
    print(f"e2e ({n_steps} steps) elapsed: {end_t - start_t} s")

    image[0].save(args.saved_image)

    if args.save_graph:
        print("Saving graphs...")
        save_pipe(pipe, args.save_graph_dir)

if __name__ == '__main__':
    heights =  [ 1024,1152, 1360, 1536]
    widths =  [1024, 1152, 1360, 1536]

    for height in heights:
        for width in widths:
            print(f"cur H : {height} W: {width}")
            parser = argparse.ArgumentParser()
            parser.add_argument( "--base", type=str, default="/share_nfs/hf_models/stable-diffusion-xl-base-1.0")
            parser.add_argument("--repo", type=str, default="/share_nfs/hf_models/SDXL-Lightning")
            parser.add_argument("--cpkt", type=str, default="sdxl_lightning_4step_unet.safetensors")
            parser.add_argument("--variant", type=str, default="fp16")
            parser.add_argument(
                "--prompt",
                type=str,
                # default="street style, detailed, raw photo, woman, face, shot on CineStill 800T",
                default="A girl smiling",
            )
            parser.add_argument("--save_graph", action="store_true")
            parser.add_argument("--load_graph", action="store_true",default=True)
            parser.add_argument("--save_graph_dir", type=str, default="cached_pipe")
            parser.add_argument("--load_graph_dir", type=str, default="cached_pipe")
            parser.add_argument("--height", type=int, default=height)
            parser.add_argument("--width", type=int, default=width)
            parser.add_argument(
                "--saved_image", type=str, required=False, default=f"sdxl-light-out-{height}-{width}.png"
            )
            parser.add_argument(
                "--src_img", type=str, required=False, default="/data/home/lijunliang/project/onediff/onediff_diffusers_extensions/sdxl-light-out-image2image.png"
            )
            parser.add_argument("--seed", type=int, default=1)
            parser.add_argument(
                "--onediff_compile", type=(lambda x: str(x).lower() in ["true", "1", "yes"]), default=True,
            )
            args = parser.parse_args()
            main(args)
```
### The complete error message
```
(sd2) lijunliang@oneflow-25:~/project/onediff/onediff_diffusers_extensions/examples$ python image_to_image_sdxl_light.py 
WARNING [2024-04-30 07:30:29] /data/home/lijunliang/testproject/onediff/src/onediff/infer_compiler/transform/manager.py:119 - Pydantic version 1.10.15 is too low, please upgrade to 2.5.2 or higher.
cur H : 1024 W: 1024
path /data/home/lijunliang/project/onediff/onediff_diffusers_extensions/sdxl-light-out-image2image.png
Loading pipeline components...: 100%|███████████████████████████████████████████████████████| 7/7 [00:00<00:00,  9.19it/s]
Loading graphs...
Warmup with running graphs...
W20240430 07:31:05.609783 507023 cuda_stream.cpp:49] Runtime version 12.1 of cuBLAS incompatible with compiletime version 12.2.
100%|███████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:46<00:00, 46.01s/it]
Normal run...
100%|███████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.75it/s]
e2e (4 steps) elapsed: 0.7437548637390137 s
cur H : 1024 W: 1152
path /data/home/lijunliang/project/onediff/onediff_diffusers_extensions/sdxl-light-out-image2image.png
Traceback (most recent call last):
  File "/data/home/lijunliang/project/onediff/onediff_diffusers_extensions/examples/image_to_image_sdxl_light.py", line 156, in <module>
    main(args)
  File "/data/home/lijunliang/project/onediff/onediff_diffusers_extensions/examples/image_to_image_sdxl_light.py", line 55, in main
    load_file(os.path.join(args.repo, args.cpkt), device="cuda")
  File "/data/home/lijunliang/anaconda3/envs/sd2/lib/python3.10/site-packages/safetensors/torch.py", line 310, in load_file
    result[k] = f.get_tensor(k)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 14.00 MiB. GPU 0 has a total capacity of 23.68 GiB of which 6.69 MiB is free. Including non-PyTorch memory, this process has 23.67 GiB memory in use. Of the allocated memory 15.32 GiB is allocated by PyTorch, and 662.02 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

### Additional context

via export ONEDIFF_DEBUG=1
I get the logs below
[image_to_image_output.txt](https://github.com/siliconflow/onediff/files/15160881/image_to_image_output.txt)
This file contains multiple start building graphs, proving that the graphs are built multiple times

**Comment by lijunliangTG** [comment]
The output pictures are in [withnocomplie.zip](https://github.com/siliconflow/onediff/files/15215579/withnocomplie.zip)
GPU running records[OUTPUT_FILE_7_withnocomplie.txt](https://github.com/siliconflow/onediff/files/15215580/OUTPUT_FILE_7_withnocomplie.txt)
The following results are based on turning off onediff_compile and deleting the following code:
```
  # del pipe
  # torch.cuda.empty_cache()
  # oneflow.cuda.empty_cache()
```
It runs normally, no errors are reported

**Comment by lijunliangTG** [comment]
This problem can be solved in two ways: a. Disable the tuning cache(adding); b. Use an available size and preheat. The source file may be a multiple of 64 resolutions from large to small.
```
heights = [1536,1360,1152,1024]
widths = [1536,1360,1152,1024]
```
