### ISSUE TITLE
failed to start webui with onediff

### ISSUE THREAD

**Issue by XRFate** [siliconflow/onediff#889]
### 

> ./venv/bin/python3 webui.py --port 8080 --share
2024-05-20 08:16:31.312412: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-05-20 08:16:32.493384: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-20 08:16:34.106512: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
*** Error loading script: onediff.py
    Traceback (most recent call last):
      File "/home/sd/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/home/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/sd/stable-diffusion-webui/extensions/onediff_sd_webui_extensions/scripts/onediff.py", line 15, in <module>
        from compile_ldm import compile_ldm_unet, SD21CompileCtx
      File "/home/sd/stable-diffusion-webui/extensions/onediff_sd_webui_extensions/compile_ldm.py", line 2, in <module>
        import oneflow as flow
      File "/home/sd/stable-diffusion-webui/venv/lib/python3.10/site-packages/oneflow/__init__.py", line 26, in <module>
        import oneflow._oneflow_internal
    ImportError: libcudnn_cnn_infer.so.8: cannot open shared object file: No such file or directory

#### nvcc
>nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0

#### nvidia

>| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4

**Comment by marigoold** [comment]
hi @XRFate maybe you can try `python3 -m pip install nvidia-cudnn-cu11` to install the dependencies
