### ISSUE TITLE
Cannot import /comfyui/custom_nodes/onediff_comfy_nodes module for custom nodes: No module named 'onediff.infer_compiler'`

### ISSUE THREAD

**Issue by alboto** [siliconflow/onediff#920]
#### A clear and concise description of what the bug is.
I want to use the onediff comfyui nodes, but after I install all dependences, I got error: No module named 'onediff.infer_compiler'
#### OS 
ubuntu
#### OneDiff git commit id
fb025baedc457571c8e6dade248ec02d4d3548a3
####  OneFlow version info
libibverbs not available, ibv_fork_init skipped
path: ['/usr/local/lib/python3.10/site-packages/oneflow']
version: 0.9.1.dev20240528+cu118
git_commit: ec7b682
cmake_build_type: Release
rdma: True
mlir: True
enterprise: False
### How To Reproduce
Steps to reproduce the behavior(code or script):
1. git clone https://github.com/siliconflow/onediff.git
2. python3 -m pip install -U --pre oneflow -f https://oneflow-pro.oss-cn-beijing.aliyuncs.com/branch/community/cu118
3. cd onediff && pip3 install --pre .
4. copy onediff_comfy_nodes into custom_nodes 
5. start comfyui

btw, if use `python3 -m pip install --pre onediff` to install onediff, also will get this error.
### The complete error message
2024-05-29 15:19:10.853 Traceback (most recent call last):
2024-05-29 15:19:10.853   File "/app/plugins/comfyui/nodes.py", line 1870, in load_custom_node
2024-05-29 15:19:10.853     module_spec.loader.exec_module(module)
2024-05-29 15:19:10.853   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2024-05-29 15:19:10.853   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-05-29 15:19:10.853   File "/app/plugins/comfyui/custom_nodes/onediff_comfy_nodes/__init__.py", line 3, in <module>
2024-05-29 15:19:10.853     from ._nodes import (
2024-05-29 15:19:10.853   File "/app/plugins/comfyui/custom_nodes/onediff_comfy_nodes/_nodes.py", line 10, in <module>
2024-05-29 15:19:10.853     from .modules.oneflow import BasicOneFlowBoosterExecutor
2024-05-29 15:19:10.853   File "/app/plugins/comfyui/custom_nodes/onediff_comfy_nodes/modules/oneflow/__init__.py", line 1, in <module>
2024-05-29 15:19:10.853     from .config import _USE_UNET_INT8, ONEDIFF_QUANTIZED_OPTIMIZED_MODELS
2024-05-29 15:19:10.853   File "/app/plugins/comfyui/custom_nodes/onediff_comfy_nodes/modules/oneflow/config.py", line 6, in <module>
2024-05-29 15:19:10.853     from onediff.infer_compiler.backends.oneflow.utils.version_util import is_community_version
2024-05-29 15:19:10.853 ModuleNotFoundError: No module named 'onediff.infer_compiler'
2024-05-29 15:19:10.853 
2024-05-29 15:19:10.853 Cannot import /app/plugins/comfyui/custom_nodes/onediff_comfy_nodes module for custom nodes: No module named 'onediff.infer_compiler'

**Comment by strint** [comment]
Please refer to this to see whether it works: https://github.com/siliconflow/onediff/issues/771

**Comment by alboto** [comment]
> Please refer to this to see whether it works: #771

Ops, it works, thanks a lot !!
I left the onediff directory in custom nodes which cause the issue
